In [242]:
#lOAD PACKAGES
import pandas as pd
import matplotlib.pyplot as plt
import os
import plotly.express as px
# Import the processing module from the same folder
from processing import load_solutions, add_kwargs_as_indices, combine_solutions, read_parquet_and_convert, add_fields
# import processing 
# from pivottablejs import pivot_ui
G_save = True

In [243]:
ss = [
    {'solution_folder': f"RTS-GMLC_envelope_benchmark_s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_e_reserve_benchmark_s", 'model_type' : 'e-reserve'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v0.5s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.8s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.9s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.10s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.11s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v1.5s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_e_reserve_compare_v1.7s", 'model_type' : 'e-reserve'},
    # {'solution_folder': f"RTS-GMLC_e_reserve_compare_v1.9s", 'model_type' : 'e-reserve'},
    ]

s_uc = []
s_ed = []
gcd_KPI_adequacy = []
gcdi_KPI_adequacy = []
for sol in ss:
    # ρ = sol['ρ']
    s = sol['solution_folder']
    s_uc_name = 's_suc' if sol['model_type'] == 'stochastic' else 's_uc'
    # s_uc_ = load_solutions(s_uc_name, os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_ed_ = load_solutions("s_ed", os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_uc.append(s_uc_)
    # s_ed.append(s_ed_)

    gcd_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcd_KPI_adequacy.parquet"))
    gcd_KPI_adequacy_ = add_fields(gcd_KPI_adequacy_, model_type = sol['model_type'], solution_id = s) 

    gcdi_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcdi_KPI_adequacy.parquet"))
    gcdi_KPI_adequacy_ = add_fields(gcdi_KPI_adequacy_, model_type = sol['model_type'], solution_id = s)

    gcd_KPI_adequacy.append(gcd_KPI_adequacy_)
    gcdi_KPI_adequacy.append(gcdi_KPI_adequacy_)

# s_uc = combine_solutions(s_uc)
# s_ed = combine_solutions(s_ed)
gcd_KPI_adequacy = pd.concat(gcd_KPI_adequacy)
gcdi_KPI_adequacy = pd.concat(gcdi_KPI_adequacy)

if 'µ' in gcdi_KPI_adequacy.columns: 
#         # out['non-conservative'] = out[['model_type', 'µ']].apply(lambda x: (x[0] !='envelope') + (x[0] =='envelope')*(x[1]<1), axis = 1)
    gcdi_KPI_adequacy['model_type'] = gcdi_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)
    gcd_KPI_adequacy['model_type'] = gcd_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)

../output/RTS-GMLC_envelope_benchmark_s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_benchmark_s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_benchmark_s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_benchmark_s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.9s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.9s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.10s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.10s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.11s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.11s/all_gcdi_KPI_adequacy.parquet

In [244]:
gcd_KPI_adequacy

,model_type,solution_id,configuration,day,OV_uc,E_fixed_cost,E_storage_discharge_MWh,reserve_cost_uc,E_storage_charge_MWh,SOE_0_MWh,...,slack_energy_reserve_down_cost_uc,required_energy_reserve_down_uc_MWh,required_energy_reserve_up_uc_MWh,slack_energy_reserve_down_uc_MWh,slack_energy_reserve_up_cost_uc,avg_marginal_energy_reserve_down_price_uc_MU_MWh,energy_reserve_down_uc_MWh,energy_reserve_cost_uc,avg_marginal_energy_reserve_up_price_uc_MU_MWh,energy_reserve_up_uc_MWh
0,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11707.961617,0.029785,3226.496681,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11477.471162,0.042446,5849.950564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13906.874641,0.042446,5221.718834,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673346.727052,0.0,13199.520906,NaN,3224.216418,12683.7,...,0.000017,1.017636e+06,8.876647e+05,6.806620e-08,0.000017,None,1.017666e+06,1.905373,None,8.877079e+05
1,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,673346.729452,0.0,13801.495348,NaN,3231.414251,12683.7,...,0.000057,1.017636e+06,8.876647e+05,2.282002e-07,0.000057,None,1.017982e+06,1.906243,None,8.882609e+05
2,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570293.678281,0.0,14540.967352,NaN,5538.673084,12683.7,...,0.000006,8.807302e+05,2.217726e+06,2.434966e-08,0.000006,None,8.807641e+05,3.098533,None,2.217768e+06
3,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,570293.677990,0.0,14546.085836,NaN,5543.791568,12683.7,...,0.000003,8.807302e+05,2.217726e+06,1.314965e-08,0.000003,None,8.807319e+05,3.098460,None,2.217728e+06
0,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11707.995165,0.029785,3226.530229,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11489.262384,0.042446,5861.741786,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13951.640898,0.042446,5266.485090,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,envelope,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11708.104658,0.029785,3226.639721,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11488.206962,0.042446,5860.686364,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13941.336786,0.042446,5256.180978,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103865,0.042446,3624.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,envelope,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103865,0.042446,3624.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [245]:
values_ = ['reserve_cost_uc','slack_reserve_up_cost_uc','slack_reserve_down_cost_uc','energy_reserve_cost_uc','slack_energy_reserve_up_cost_uc','slack_energy_reserve_down_cost_uc']
values_ += [
    'reserve_up_uc_MWh', 'reserve_down_uc_MWh', 'slack_reserve_up_uc_MWh', 'slack_reserve_down_uc_MWh',
    'required_reserve_up_uc_MWh', 'required_reserve_down_uc_MWh',
    'energy_reserve_up_uc_MWh', 'energy_reserve_down_uc_MWh', 'slack_energy_reserve_up_uc_MWh', 'slack_energy_reserve_down_uc_MWh',
    'required_energy_reserve_up_uc_MWh', 'required_energy_reserve_down_uc_MWh'
]
values_ += ['EOV',]
values_ = [v for v in values_ if v in gcd_KPI_adequacy.columns]
pivot = pd.pivot_table(
    gcd_KPI_adequacy,
    index=['day', 'solution_id'],
    columns='model_type',
    values=values_
)
print(pivot)    
# pivot

                                                EOV                 \
model_type                             conservative      e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s              NaN  435074.858611
    RTS-GMLC_envelope_benchmark_s     473139.475829            NaN
    RTS-GMLC_envelope_compare_v1.10s  463176.717185            NaN
    RTS-GMLC_envelope_compare_v1.11s  463176.717185            NaN
    RTS-GMLC_envelope_compare_v1.8s   473139.475829            NaN
    RTS-GMLC_envelope_compare_v1.9s   473139.475829            NaN
3   RTS-GMLC_e_reserve_benchmark_s              NaN  439090.494318
    RTS-GMLC_envelope_benchmark_s     458327.211666            NaN
    RTS-GMLC_envelope_compare_v1.10s  436283.821339            NaN
    RTS-GMLC_envelope_compare_v1.11s  436283.821339            NaN
    RTS-GMLC_envelope_compare_v1.8s   458327.211676            NaN
    RTS-GMLC_envelope_compare_v1.9s   458327.211673            NaN

                                                    energy_reserve_cost_uc  \
model_type                                 envelope              e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s              NaN               1.905808
    RTS-GMLC_envelope_benchmark_s     577492.048552                    NaN
    RTS-GMLC_envelope_compare_v1.10s  571018.903769                    NaN
    RTS-GMLC_envelope_compare_v1.11s  571018.903769                    NaN
    RTS-GMLC_envelope_compare_v1.8s   577492.048552                    NaN
    RTS-GMLC_envelope_compare_v1.9s   577492.048552                    NaN
3   RTS-GMLC_e_reserve_benchmark_s              NaN               3.098496
    RTS-GMLC_envelope_benchmark_s     512433.649559                    NaN
    RTS-GMLC_envelope_compare_v1.10s  530619.901345                    NaN
    RTS-GMLC_envelope_compare_v1.11s  530619.901345                    NaN
    RTS-GMLC_envelope_compare_v1.8s   512433.649561                    NaN
    RTS-GMLC_envelope_compare_v1.9s   512433.649561                    NaN

                                     energy_reserve_down_uc_MWh  \
model_type                                            e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                 1.017824e+06
    RTS-GMLC_envelope_benchmark_s                           NaN
    RTS-GMLC_envelope_compare_v1.10s                        NaN
    RTS-GMLC_envelope_compare_v1.11s                        NaN
    RTS-GMLC_envelope_compare_v1.8s                         NaN
    RTS-GMLC_envelope_compare_v1.9s                         NaN
3   RTS-GMLC_e_reserve_benchmark_s                 8.807480e+05
    RTS-GMLC_envelope_benchmark_s                           NaN
    RTS-GMLC_envelope_compare_v1.10s                        NaN
    RTS-GMLC_envelope_compare_v1.11s                        NaN
    RTS-GMLC_envelope_compare_v1.8s                         NaN
    RTS-GMLC_envelope_compare_v1.9s                         NaN

                                     energy_reserve_up_uc_MWh  \
model_type                                          e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s               8.879844e+05
    RTS-GMLC_envelope_benchmark_s                         NaN
    RTS-GMLC_envelope_compare_v1.10s                      NaN
    RTS-GMLC_envelope_compare_v1.11s                      NaN
    RTS-GMLC_envelope_compare_v1.8s                       NaN
    RTS-GMLC_envelope_compare_v1.9s                       NaN
3   RTS-GMLC_e_reserve_benchmark_s               2.217748e+06
    RTS-GMLC_envelope_benchmark_s                         NaN
    RTS-GMLC_envelope_compare_v1.10s                      NaN
    RTS-GMLC_envelope_compare_v1.11s                      NaN
    RTS-GMLC_envelope_compare_v1.8s                       NaN
    RTS-GMLC_envelope_compare_v1.9s                       NaN

                                     required_energy_reserve_down_uc_MWh  \
model_type                                                     e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                          1.017636e+06
    RTS-GMLC_envelope_benchmark_s                                    NaN
    RTS-GMLC_envelope_compare_v1.10s                                 NaN
    RTS-GMLC_envelope_compare_v1.11s                                 NaN
    RTS-GMLC_envelope_compare_v1.8s                                  NaN
    RTS-GMLC_envelope_compare_v1.9s                                  NaN
3   RTS-GMLC_e_reserve_benchmark_s                          8.807302e+05
    RTS-GMLC_envelope_benchmark_s                                    NaN
    RTS-GMLC_envelope_compare_v1.10s                                 NaN
    RTS-GMLC_envelope_compare_v1.11s                                 NaN
    RTS-GMLC_envelope_compare_v1.8s                                  NaN
    RTS-GMLC_envelope_compare_v1.9s                                  NaN

                                     required_energy_reserve_up_uc_MWh  \
model_type                                                   e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                        8.876647e+05
    RTS-GMLC_envelope_benchmark_s                                  NaN
    RTS-GMLC_envelope_compare_v1.10s                               NaN
    RTS-GMLC_envelope_compare_v1.11s                               NaN
    RTS-GMLC_envelope_compare_v1.8s                                NaN
    RTS-GMLC_envelope_compare_v1.9s                                NaN
3   RTS-GMLC_e_reserve_benchmark_s                        2.217726e+06
    RTS-GMLC_envelope_benchmark_s                                  NaN
    RTS-GMLC_envelope_compare_v1.10s                               NaN
    RTS-GMLC_envelope_compare_v1.11s                               NaN
    RTS-GMLC_envelope_compare_v1.8s                                NaN
    RTS-GMLC_envelope_compare_v1.9s                                NaN

                                     required_reserve_down_uc_MWh  \
model_type                                           conservative
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                            NaN
    RTS-GMLC_envelope_benchmark_s                    14812.233953
    RTS-GMLC_envelope_compare_v1.10s                 14812.233953
    RTS-GMLC_envelope_compare_v1.11s                 14812.233953
    RTS-GMLC_envelope_compare_v1.8s                  14812.233953
    RTS-GMLC_envelope_compare_v1.9s                  14812.233953
3   RTS-GMLC_e_reserve_benchmark_s                            NaN
    RTS-GMLC_envelope_benchmark_s                    15960.645167
    RTS-GMLC_envelope_compare_v1.10s                 15960.645167
    RTS-GMLC_envelope_compare_v1.11s                 15960.645167
    RTS-GMLC_envelope_compare_v1.8s                  15960.645167
    RTS-GMLC_envelope_compare_v1.9s                  15960.645167

                                                    ...  \
model_type                                envelope  ...
day solution_id                                     ...
2   RTS-GMLC_e_reserve_benchmark_s             NaN  ...
    RTS-GMLC_envelope_benchmark_s     14812.233953  ...
    RTS-GMLC_envelope_compare_v1.10s  14812.233953  ...
    RTS-GMLC_envelope_compare_v1.11s  14812.233953  ...
    RTS-GMLC_envelope_compare_v1.8s   14812.233953  ...
    RTS-GMLC_envelope_compare_v1.9s   14812.233953  ...
3   RTS-GMLC_e_reserve_benchmark_s             NaN  ...
    RTS-GMLC_envelope_benchmark_s     15960.645167  ...
    RTS-GMLC_envelope_compare_v1.10s  15960.645167  ...
    RTS-GMLC_envelope_compare_v1.11s  15960.645167  ...
    RTS-GMLC_envelope_compare_v1.8s   15960.645167  ...
    RTS-GMLC_envelope_compare_v1.9s   15960.645167  ...

                                     slack_energy_reserve_up_cost_uc  \
model_type                                                 e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                          0.000037
    RTS-GMLC_envelope_benchmark_s                                NaN
    RTS-GMLC_envelope_compare_v1.10s                             NaN
    RTS-GMLC_envelope_compare_v1.11s                             NaN
    RTS-GMLC_envelope_compare_v1.8s                              NaN
    RTS-GMLC_envelope_compare_v1.9s                              NaN
3   RTS-GMLC_e_reserve_benchmark_s                          0.000004
    RTS-GMLC_envelope_benchmark_s                                NaN
    RTS-GMLC_envelope_compare_v1.10s                             NaN
    RTS-GMLC_envelope_compare_v1.11s                             NaN
    RTS-GMLC_envelope_compare_v1.8s                              NaN
    RTS-GMLC_envelope_compare_v1.9s                              NaN

                                     slack_energy_reserve_up_uc_MWh  \
model_type                                                e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                     1.480726e-07
    RTS-GMLC_envelope_benchmark_s                               NaN
    RTS-GMLC_envelope_compare_v1.10s                            NaN
    RTS-GMLC_envelope_compare_v1.11s                            NaN
    RTS-GMLC_envelope_compare_v1.8s                             NaN
    RTS-GMLC_envelope_compare_v1.9s                             NaN
3   RTS-GMLC_e_reserve_benchmark_s                     1.671302e-08
    RTS-GMLC_envelope_benchmark_s                               NaN
    RTS-GMLC_envelope_compare_v1.10s                            NaN
    RTS-GMLC_envelope_compare_v1.11s                            NaN
    RTS-GMLC_envelope_compare_v1.8s                             NaN
    RTS-GMLC_envelope_compare_v1.9s                             NaN

                                     slack_reserve_down_cost_uc                \
model_type                                         conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                          NaN           NaN
    RTS-GMLC_envelope_benchmark_s                  6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.10s               6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.11s               6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.8s                6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.9s                6.366712e-09  2.174425e-08
3   RTS-GMLC_e_reserve_benchmark_s                          NaN           NaN
    RTS-GMLC_envelope_benchmark_s                  9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.10s               9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.11s               9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.8s                9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.9s                9.083310e-09  2.483200e-09

                                     slack_reserve_down_uc_MWh                \
model_type                                        conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                         NaN           NaN
    RTS-GMLC_envelope_benchmark_s                 2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.10s              2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.11s              2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s               2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.9s               2.546685e-11  8.697700e-11
3   RTS-GMLC_e_reserve_benchmark_s                         NaN           NaN
    RTS-GMLC_envelope_benchmark_s                 3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.10s              3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.11s              3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s               3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.9s               3.633324e-11  9.932801e-12

                                     slack_reserve_up_cost_uc                \
model_type                                       conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                        NaN           NaN
    RTS-GMLC_envelope_benchmark_s                6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.10s             6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.11s             6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.8s              6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.9s              6.366712e-09  2.174425e-08
3   RTS-GMLC_e_reserve_benchmark_s                        NaN           NaN
    RTS-GMLC_envelope_benchmark_s                8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.10s             8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.11s             8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.8s              8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.9s              8.559819e-09  2.483200e-09

                                     slack_reserve_up_uc_MWh
model_type                                      conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                       NaN           NaN
    RTS-GMLC_envelope_benchmark_s               2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.10s            2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.11s            2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s             2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.9s             2.546685e-11  8.697700e-11
3   RTS-GMLC_e_reserve_benchmark_s                       NaN           NaN
    RTS-GMLC_envelope_benchmark_s               3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.10s            3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.11s            3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s             3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.9s             3.423928e-11  9.932801e-12

[12 rows x 30 columns]

In [246]:
values_

['reserve_cost_uc',
 'slack_reserve_up_cost_uc',
 'slack_reserve_down_cost_uc',
 'energy_reserve_cost_uc',
 'slack_energy_reserve_up_cost_uc',
 'slack_energy_reserve_down_cost_uc',
 'reserve_up_uc_MWh',
 'reserve_down_uc_MWh',
 'slack_reserve_up_uc_MWh',
 'slack_reserve_down_uc_MWh',
 'required_reserve_up_uc_MWh',
 'required_reserve_down_uc_MWh',
 'energy_reserve_up_uc_MWh',
 'energy_reserve_down_uc_MWh',
 'slack_energy_reserve_up_uc_MWh',
 'slack_energy_reserve_down_uc_MWh',
 'required_energy_reserve_up_uc_MWh',
 'required_energy_reserve_down_uc_MWh',
 'EOV']

In [247]:
# pivot.to_csv('pivot.csv')
# gcd_KPI_adequacy.to_csv('test.csv')
#

In [248]:
from itertools import product

days = [3]
scalar = []
for sol, day in product(ss, days):
    s = sol['solution_folder']
    scalar_ = pd.read_parquet(os.path.join("..", "output", s, f'n_{day}','s_uc_scalar.parquet'))
    scalar_['day'] = day
    scalar_['solution_id'] = sol['solution_folder']
    # scalar_.model_type = sol['model_type']
    scalar.append(scalar_)        

scalar = pd.concat(scalar)

In [249]:
# scalar.to_csv('scalar.csv', index=False)

In [250]:
scalar

,objective_value,termination_status,OPEX,day,configuration,solution_id
0,580563.560828,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
1,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_benchmark_s
0,570293.677990,OPTIMAL,570290.579524,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_e_reserve_benchmark_s
1,570293.678281,OPTIMAL,570290.579737,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_e_reserve_benchmark_s
0,580563.560828,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.8s
1,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.8s
0,580563.560828,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.9s
1,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.9s
0,580563.560828,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.10s
1,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.10s
0,580563.560828,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.11s
1,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.11s

In [251]:
gcdi_KPI_adequacy['µ']

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
    ...
3    0.5
0    1.0
1    0.5
2    1.0
3    0.5
Name: µ, Length: 1608, dtype: float64

In [252]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy.model_type == 'conservative')  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
265,580563.560828,436283.821340,RTS-GMLC_envelope_benchmark_s,demand_1
265,580563.560828,436283.821342,RTS-GMLC_envelope_compare_v1.8s,demand_1
265,580563.560828,436283.821339,RTS-GMLC_envelope_compare_v1.9s,demand_1
2,580563.560828,436283.821339,RTS-GMLC_envelope_compare_v1.10s,demand_1
2,580563.560828,436283.821339,RTS-GMLC_envelope_compare_v1.11s,demand_1

In [253]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy['µ'] == 0.5)  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
365,570290.621895,530619.901346,RTS-GMLC_envelope_benchmark_s,demand_1
365,570293.678281,424132.904044,RTS-GMLC_e_reserve_benchmark_s,demand_1
365,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.8s,demand_1
365,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.9s,demand_1
3,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.10s,demand_1
3,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.11s,demand_1

In [254]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy.model_type == 'e-reserve')  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
265,570293.677990,424132.904044,RTS-GMLC_e_reserve_benchmark_s,demand_1
365,570293.678281,424132.904044,RTS-GMLC_e_reserve_benchmark_s,demand_1

In [255]:
gcdi_KPI_adequacy

,model_type,solution_id,configuration,day,iteration,LLD_h,ENS_MWh,input_load_MWh,CURD_h,CUR_MWh,...,slack_energy_reserve_up_cost_uc,slack_energy_reserve_down_cost_uc,avg_marginal_energy_reserve_down_price_uc_MU_MWh,avg_marginal_energy_reserve_up_price_uc_MU_MWh,slack_energy_reserve_down_uc_MWh,required_energy_reserve_up_uc_MWh,slack_energy_reserve_up_uc_MWh,required_energy_reserve_down_uc_MWh,energy_reserve_down_uc_MWh,energy_reserve_up_uc_MWh
0,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_86,0,3.714700e-14,41497.991268,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_91,0,3.347293e-17,38482.750638,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_48,0,7.594515e-14,42991.007672,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_21,0,1.050402e-14,46377.127336,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_16,0,3.143277e-12,38704.887948,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,demand_1,0,4.803482e-16,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,conservative,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,1.376248e-12,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,envelope,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,1.296158e-15,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,conservative,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,5.937515e-16,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,envelope,RTS-GMLC_envelope_compare_v1.11s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,demand_1,0,4.803482e-16,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [256]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') #&  (gcdi_KPI_adequacy.day == 3)
for k,v in gcdi_KPI_adequacy.loc[filter_,:].groupby(['day', 'µ', 'model_type']):
    print(v[['objective_value_uc','objective_value', 'day', 'µ', 'model_type', 'SOE_T_MWh']])

     objective_value_uc  objective_value  day    µ model_type   SOE_T_MWh
165       673346.727052    425837.828561    2  0.5  e-reserve  906.645654
     objective_value_uc  objective_value  day    µ model_type    SOE_T_MWh
165       673344.851286    571018.903769    2  0.5   envelope  8168.973463
165       673344.851286    571018.903769    2  0.5   envelope  8168.973463
165       673344.851286    571018.903769    2  0.5   envelope  8168.973463
1         673344.851286    571018.903769    2  0.5   envelope  8168.973463
1         673344.851286    571018.903769    2  0.5   envelope  8168.973463
    objective_value_uc  objective_value  day    µ    model_type    SOE_T_MWh
65       673344.851285    463176.717185    2  1.0  conservative  2813.938396
65       673344.851285    463176.717185    2  1.0  conservative  2813.938396
65       673344.851285    463176.717185    2  1.0  conservative  2813.938396
0        673344.851285    463176.717185    2  1.0  conservative  2813.938396
0        673344.851285    463176.717185    2  1.0  conservative  2813.938396
    objective_value_uc  objective_value  day    µ model_type  SOE_T_MWh
65       673346.729452    409516.584938    2  1.0  e-reserve  51.154903
     objective_value_uc  objective_value  day    µ model_type     SOE_T_MWh
365       570293.678281    424132.904044    3  0.5  e-reserve  1.293039e-10
     objective_value_uc  objective_value  day    µ model_type   SOE_T_MWh
365       570290.621895    530619.901346    3  0.5   envelope  5337.98547
365       570290.621895    530619.901345    3  0.5   envelope  5337.98547
365       570290.621895    530619.901345    3  0.5   envelope  5337.98547
3         570290.621895    530619.901345    3  0.5   envelope  5337.98547
3         570290.621895    530619.901345    3  0.5   envelope  5337.98547
     objective_value_uc  objective_value  day    µ    model_type     SOE_T_MWh
265       580563.560828    436283.821340    3  1.0  conservative  4.118780e-10
265       580563.560828    436283.821342    3  1.0  conservative  3.880825e-09
265       580563.560828    436283.821339    3  1.0  conservative  5.971756e-13
2         580563.560828    436283.821339    3  1.0  conservative  5.971756e-13
2         580563.560828    436283.821339    3  1.0  conservative  5.971756e-13
     objective_value_uc  objective_value  day    µ model_type     SOE_T_MWh
265        570293.67799    424132.904044    3  1.0  e-reserve -7.133918e-12

In [257]:
gcdi_KPI_adequacy[['objective_value_uc','objective_value','solution_id', 'day', 'µ', 'model_type']]

,objective_value_uc,objective_value,solution_id,day,µ,model_type
0,673344.851285,450946.521613,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
1,673344.851285,390804.266707,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
2,673344.851285,478871.229947,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
3,673344.851285,549114.153620,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
4,673344.851285,393903.636144,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
...,...,...,...,...,...,...
3,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.10s,3,0.5,envelope
0,673344.851285,463176.717185,RTS-GMLC_envelope_compare_v1.11s,2,1.0,conservative
1,673344.851286,571018.903769,RTS-GMLC_envelope_compare_v1.11s,2,0.5,envelope
2,580563.560828,436283.821339,RTS-GMLC_envelope_compare_v1.11s,3,1.0,conservative
3,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.11s,3,0.5,envelope

In [258]:
x = 436283.821342
y = 436283.821339
print( (x-y)/y)

6.876176674651827e-12