In [1]:
#lOAD PACKAGES
import pandas as pd
import matplotlib.pyplot as plt
import os
import plotly.express as px
# Import the processing module from the same folder
from processing import load_solutions, add_kwargs_as_indices, combine_solutions, read_parquet_and_convert, add_fields
# import processing 
# from pivottablejs import pivot_ui
G_save = True

In [2]:
ss = [
    {'solution_folder': f"RTS-GMLC_envelope_benchmark_su", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_e_reserve_benchmark_su", 'model_type' : 'e-reserve'},
    {'solution_folder': f"RTS-GMLC_v5.2.2.3.3su", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_v6.2.2.3.3su", 'model_type' : 'e-reserve'},
    ]

s_uc = []
s_ed = []
gcd_KPI_adequacy = []
gcdi_KPI_adequacy = []
for sol in ss:
    # ρ = sol['ρ']
    s = sol['solution_folder']
    s_uc_name = 's_suc' if sol['model_type'] == 'stochastic' else 's_uc'
    # s_uc_ = load_solutions(s_uc_name, os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_ed_ = load_solutions("s_ed", os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_uc.append(s_uc_)
    # s_ed.append(s_ed_)

    gcd_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcd_KPI_adequacy.parquet"))
    gcd_KPI_adequacy_ = add_fields(gcd_KPI_adequacy_, model_type = sol['model_type'], solution_id = s) 

    gcdi_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcdi_KPI_adequacy.parquet"))
    gcdi_KPI_adequacy_ = add_fields(gcdi_KPI_adequacy_, model_type = sol['model_type'], solution_id = s)

    gcd_KPI_adequacy.append(gcd_KPI_adequacy_)
    gcdi_KPI_adequacy.append(gcdi_KPI_adequacy_)

# s_uc = combine_solutions(s_uc)
# s_ed = combine_solutions(s_ed)
gcd_KPI_adequacy = pd.concat(gcd_KPI_adequacy)
gcdi_KPI_adequacy = pd.concat(gcdi_KPI_adequacy)

if 'µ' in gcdi_KPI_adequacy.columns: 
#         # out['non-conservative'] = out[['model_type', 'µ']].apply(lambda x: (x[0] !='envelope') + (x[0] =='envelope')*(x[1]<1), axis = 1)
    gcdi_KPI_adequacy['model_type'] = gcdi_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)
    gcd_KPI_adequacy['model_type'] = gcd_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)

../output/RTS-GMLC_envelope_benchmark_su/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_benchmark_su/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_benchmark_su/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_benchmark_su/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_v5.2.2.3.3su/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_v5.2.2.3.3su/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_v6.2.2.3.3su/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_v6.2.2.3.3su/all_gcdi_KPI_adequacy.parquet

In [3]:
gcd_KPI_adequacy

,model_type,solution_id,configuration,day,OV_uc,E_fixed_cost,E_storage_discharge_MWh,reserve_cost_uc,E_storage_charge_MWh,SOE_0_MWh,...,slack_energy_reserve_down_cost_uc,required_energy_reserve_down_uc_MWh,required_energy_reserve_up_uc_MWh,slack_energy_reserve_down_uc_MWh,slack_energy_reserve_up_cost_uc,avg_marginal_energy_reserve_down_price_uc_MU_MWh,energy_reserve_down_uc_MWh,energy_reserve_cost_uc,avg_marginal_energy_reserve_up_price_uc_MU_MWh,energy_reserve_up_uc_MWh
0,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_7_dn_0_7,2,673344.851286,0.0,9142.800162,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,conservative,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851286,0.0,11978.695841,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_7_dn_0_7,3,570290.621895,0.0,13102.937237,0.042446,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,conservative,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560829,0.0,14828.103865,0.042446,3624.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_e_reserve_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,2,673346.734391,0.0,14581.001018,NaN,3349.291564,12683.7,...,8.208746e-05,1.017636e+06,8.876647e+05,3.283499e-07,8.205350e-05,None,1.018143e+06,1.906665,None,8.885219e+05
1,e-reserve,RTS-GMLC_e_reserve_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,3,570293.677921,0.0,15066.559235,NaN,3894.646298,12683.7,...,4.896175e-07,8.807302e+05,2.217726e+06,1.958470e-09,4.896175e-07,None,8.807325e+05,3.098459,None,2.217727e+06
0,envelope,RTS-GMLC_v5.2.2.3.3su,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621900,0.0,10169.779240,0.042448,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,envelope,RTS-GMLC_v5.2.2.3.3su,base_ramp_storage_envelopes_up_0_7_dn_0_7,3,570290.621895,0.0,13428.608538,0.042446,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,conservative,RTS-GMLC_v5.2.2.3.3su,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560829,0.0,14801.565126,0.042446,3593.809791,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_v6.2.2.3.3su,base_ramp_storage_envelopes_up_1_dn_1,3,570293.677921,0.0,15066.559235,NaN,3894.646298,12683.7,...,4.896175e-07,8.807302e+05,2.217726e+06,1.958470e-09,4.896175e-07,None,8.807325e+05,3.098459,None,2.217727e+06

In [4]:
values_ = ['reserve_cost_uc','slack_reserve_up_cost_uc','slack_reserve_down_cost_uc','energy_reserve_cost_uc','slack_energy_reserve_up_cost_uc','slack_energy_reserve_down_cost_uc']
values_ += [
    'reserve_up_uc_MWh', 'reserve_down_uc_MWh', 'slack_reserve_up_uc_MWh', 'slack_reserve_down_uc_MWh',
    'required_reserve_up_uc_MWh', 'required_reserve_down_uc_MWh',
    'energy_reserve_up_uc_MWh', 'energy_reserve_down_uc_MWh', 'slack_energy_reserve_up_uc_MWh', 'slack_energy_reserve_down_uc_MWh',
    'required_energy_reserve_up_uc_MWh', 'required_energy_reserve_down_uc_MWh'
]
values_ += ['EOV',]
values_ = [v for v in values_ if v in gcd_KPI_adequacy.columns]
pivot = pd.pivot_table(
    gcd_KPI_adequacy,
    index=['day', 'solution_id'],
    columns='model_type',
    values=values_
)
print(pivot)    
# pivot

                                               EOV                 \
model_type                            conservative      e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su            NaN  408507.321975
    RTS-GMLC_envelope_benchmark_su   463176.717185            NaN
3   RTS-GMLC_e_reserve_benchmark_su            NaN  424132.904044
    RTS-GMLC_envelope_benchmark_su   436283.821339            NaN
    RTS-GMLC_v5.2.2.3.3su            435479.056699            NaN
    RTS-GMLC_v6.2.2.3.3su                      NaN  424132.904044

                                                   energy_reserve_cost_uc  \
model_type                                envelope              e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su            NaN               1.906665
    RTS-GMLC_envelope_benchmark_su   547932.838952                    NaN
3   RTS-GMLC_e_reserve_benchmark_su            NaN               3.098459
    RTS-GMLC_envelope_benchmark_su   498001.992639                    NaN
    RTS-GMLC_v5.2.2.3.3su            494358.443530                    NaN
    RTS-GMLC_v6.2.2.3.3su                      NaN               3.098459

                                    energy_reserve_down_uc_MWh  \
model_type                                           e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su               1.018143e+06
    RTS-GMLC_envelope_benchmark_su                         NaN
3   RTS-GMLC_e_reserve_benchmark_su               8.807325e+05
    RTS-GMLC_envelope_benchmark_su                         NaN
    RTS-GMLC_v5.2.2.3.3su                                  NaN
    RTS-GMLC_v6.2.2.3.3su                         8.807325e+05

                                    energy_reserve_up_uc_MWh  \
model_type                                         e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su             8.885219e+05
    RTS-GMLC_envelope_benchmark_su                       NaN
3   RTS-GMLC_e_reserve_benchmark_su             2.217727e+06
    RTS-GMLC_envelope_benchmark_su                       NaN
    RTS-GMLC_v5.2.2.3.3su                                NaN
    RTS-GMLC_v6.2.2.3.3su                       2.217727e+06

                                    required_energy_reserve_down_uc_MWh  \
model_type                                                    e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                        1.017636e+06
    RTS-GMLC_envelope_benchmark_su                                  NaN
3   RTS-GMLC_e_reserve_benchmark_su                        8.807302e+05
    RTS-GMLC_envelope_benchmark_su                                  NaN
    RTS-GMLC_v5.2.2.3.3su                                           NaN
    RTS-GMLC_v6.2.2.3.3su                                  8.807302e+05

                                    required_energy_reserve_up_uc_MWh  \
model_type                                                  e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                      8.876647e+05
    RTS-GMLC_envelope_benchmark_su                                NaN
3   RTS-GMLC_e_reserve_benchmark_su                      2.217726e+06
    RTS-GMLC_envelope_benchmark_su                                NaN
    RTS-GMLC_v5.2.2.3.3su                                         NaN
    RTS-GMLC_v6.2.2.3.3su                                2.217726e+06

                                    required_reserve_down_uc_MWh  \
model_type                                          conservative
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                          NaN
    RTS-GMLC_envelope_benchmark_su                  14812.233953
3   RTS-GMLC_e_reserve_benchmark_su                          NaN
    RTS-GMLC_envelope_benchmark_su                  15960.645167
    RTS-GMLC_v5.2.2.3.3su                           15960.645167
    RTS-GMLC_v6.2.2.3.3su                                    NaN

                                                   ...  \
model_type                               envelope  ...
day solution_id                                    ...
2   RTS-GMLC_e_reserve_benchmark_su           NaN  ...
    RTS-GMLC_envelope_benchmark_su   14812.233953  ...
3   RTS-GMLC_e_reserve_benchmark_su           NaN  ...
    RTS-GMLC_envelope_benchmark_su   15960.645167  ...
    RTS-GMLC_v5.2.2.3.3su            15960.645167  ...
    RTS-GMLC_v6.2.2.3.3su                     NaN  ...

                                    slack_energy_reserve_up_cost_uc  \
model_type                                                e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                    8.205350e-05
    RTS-GMLC_envelope_benchmark_su                              NaN
3   RTS-GMLC_e_reserve_benchmark_su                    4.896175e-07
    RTS-GMLC_envelope_benchmark_su                              NaN
    RTS-GMLC_v5.2.2.3.3su                                       NaN
    RTS-GMLC_v6.2.2.3.3su                              4.896175e-07

                                    slack_energy_reserve_up_uc_MWh  \
model_type                                               e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                   3.282140e-07
    RTS-GMLC_envelope_benchmark_su                             NaN
3   RTS-GMLC_e_reserve_benchmark_su                   1.958470e-09
    RTS-GMLC_envelope_benchmark_su                             NaN
    RTS-GMLC_v5.2.2.3.3su                                      NaN
    RTS-GMLC_v6.2.2.3.3su                             1.958470e-09

                                    slack_reserve_down_cost_uc                \
model_type                                        conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                        NaN           NaN
    RTS-GMLC_envelope_benchmark_su                2.834335e-09  1.547778e-08
3   RTS-GMLC_e_reserve_benchmark_su                        NaN           NaN
    RTS-GMLC_envelope_benchmark_su                1.244642e-08  5.744220e-09
    RTS-GMLC_v5.2.2.3.3su                         1.268932e-08  5.494858e-08
    RTS-GMLC_v6.2.2.3.3su                                  NaN           NaN

                                    slack_reserve_down_uc_MWh                \
model_type                                       conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                       NaN           NaN
    RTS-GMLC_envelope_benchmark_su               1.133734e-11  6.191113e-11
3   RTS-GMLC_e_reserve_benchmark_su                       NaN           NaN
    RTS-GMLC_envelope_benchmark_su               4.978570e-11  2.297688e-11
    RTS-GMLC_v5.2.2.3.3su                        5.075726e-11  2.197943e-10
    RTS-GMLC_v6.2.2.3.3su                                 NaN           NaN

                                    slack_reserve_up_cost_uc                \
model_type                                      conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                      NaN           NaN
    RTS-GMLC_envelope_benchmark_su              2.834335e-09  1.547778e-08
3   RTS-GMLC_e_reserve_benchmark_su                      NaN           NaN
    RTS-GMLC_envelope_benchmark_su              1.172911e-08  5.744220e-09
    RTS-GMLC_v5.2.2.3.3su                       1.195800e-08  5.548552e-08
    RTS-GMLC_v6.2.2.3.3su                                NaN           NaN

                                    slack_reserve_up_uc_MWh
model_type                                     conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_su                     NaN           NaN
    RTS-GMLC_envelope_benchmark_su             1.133734e-11  6.191113e-11
3   RTS-GMLC_e_reserve_benchmark_su                     NaN           NaN
    RTS-GMLC_envelope_benchmark_su             4.691644e-11  2.297688e-11
    RTS-GMLC_v5.2.2.3.3su                      4.783201e-11  2.219421e-10
    RTS-GMLC_v6.2.2.3.3su                               NaN           NaN

[6 rows x 30 columns]

In [5]:
values_

['reserve_cost_uc',
 'slack_reserve_up_cost_uc',
 'slack_reserve_down_cost_uc',
 'energy_reserve_cost_uc',
 'slack_energy_reserve_up_cost_uc',
 'slack_energy_reserve_down_cost_uc',
 'reserve_up_uc_MWh',
 'reserve_down_uc_MWh',
 'slack_reserve_up_uc_MWh',
 'slack_reserve_down_uc_MWh',
 'required_reserve_up_uc_MWh',
 'required_reserve_down_uc_MWh',
 'energy_reserve_up_uc_MWh',
 'energy_reserve_down_uc_MWh',
 'slack_energy_reserve_up_uc_MWh',
 'slack_energy_reserve_down_uc_MWh',
 'required_energy_reserve_up_uc_MWh',
 'required_energy_reserve_down_uc_MWh',
 'EOV']

In [6]:
# pivot.to_csv('pivot.csv')
# gcd_KPI_adequacy.to_csv('test.csv')
#

In [7]:
from itertools import product

days = [3]
scalar = []
for sol, day in product(ss, days):
    s = sol['solution_folder']
    scalar_ = pd.read_parquet(os.path.join("..", "output", s, f'n_{day}','s_uc_scalar.parquet'))
    scalar_['day'] = day
    scalar_['solution_id'] = sol['solution_folder']
    # scalar_.model_type = sol['model_type']
    scalar.append(scalar_)        

scalar = pd.concat(scalar)

In [8]:
# scalar.to_csv('scalar.csv', index=False)

In [9]:
scalar

,objective_value,termination_status,OPEX,day,configuration,solution_id
0,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_7_dn_0_7,RTS-GMLC_envelope_benchmark_su
1,580563.560829,OPTIMAL,580563.518383,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_su
2,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_benchmark_su
0,570293.677921,OPTIMAL,570290.579461,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_e_reserve_benchmark_su
0,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_7_dn_0_7,RTS-GMLC_v5.2.2.3.3su
1,580563.560829,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_v5.2.2.3.3su
2,570290.621900,OPTIMAL,570290.579452,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_v5.2.2.3.3su
0,570293.677921,OPTIMAL,570290.579461,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_v6.2.2.3.3su

In [10]:
gcdi_KPI_adequacy['µ']

0    1.0
1    0.5
2    0.7
3    0.7
4    1.0
5    0.5
0    1.0
1    1.0
0    0.7
1    1.0
2    0.5
0    1.0
Name: µ, dtype: float64

In [11]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy.model_type == 'conservative')  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
4,580563.560829,436283.821339,RTS-GMLC_envelope_benchmark_su,demand_1
1,580563.560829,435479.056699,RTS-GMLC_v5.2.2.3.3su,demand_1

In [12]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy['µ'] == 0.5)  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
5,570290.621895,530619.901346,RTS-GMLC_envelope_benchmark_su,demand_1
2,570290.621900,530174.914631,RTS-GMLC_v5.2.2.3.3su,demand_1

In [13]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy.model_type == 'e-reserve')  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
1,570293.677921,424132.904044,RTS-GMLC_e_reserve_benchmark_su,demand_1
0,570293.677921,424132.904044,RTS-GMLC_v6.2.2.3.3su,demand_1

In [14]:
gcdi_KPI_adequacy

,model_type,solution_id,configuration,day,iteration,LLD_h,ENS_MWh,input_load_MWh,CURD_h,CUR_MWh,...,slack_energy_reserve_up_cost_uc,slack_energy_reserve_down_cost_uc,avg_marginal_energy_reserve_down_price_uc_MU_MWh,avg_marginal_energy_reserve_up_price_uc_MU_MWh,slack_energy_reserve_down_uc_MWh,required_energy_reserve_up_uc_MWh,slack_energy_reserve_up_uc_MWh,required_energy_reserve_down_uc_MWh,energy_reserve_down_uc_MWh,energy_reserve_up_uc_MWh
0,conservative,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,1.512780e-13,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,3.376189e-17,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_7_dn_0_7,2,demand_1,0,1.602923e-11,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_7_dn_0_7,3,demand_1,0,8.721357e-17,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,conservative,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,7.114868e-17,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,envelope,RTS-GMLC_envelope_benchmark_su,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,demand_1,0,6.376473e-12,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_e_reserve_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,3.471052e-16,42126.249053,0,0.0,...,8.205350e-05,8.208746e-05,None,None,3.283499e-07,8.876647e+05,3.282140e-07,1.017636e+06,1.018143e+06,8.885219e+05
1,e-reserve,RTS-GMLC_e_reserve_benchmark_su,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,4.247162e-16,43563.011255,0,0.0,...,4.896175e-07,4.896175e-07,None,None,1.958470e-09,2.217726e+06,1.958470e-09,8.807302e+05,8.807325e+05,2.217727e+06
0,envelope,RTS-GMLC_v5.2.2.3.3su,base_ramp_storage_envelopes_up_0_7_dn_0_7,3,demand_1,0,1.456491e-14,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_v5.2.2.3.3su,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,5.788766e-14,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_v5.2.2.3.3su,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,demand_1,0,1.014229e-15,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_v6.2.2.3.3su,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,4.247162e-16,43563.011255,0,0.0,...,4.896175e-07,4.896175e-07,None,None,1.958470e-09,2.217726e+06,1.958470e-09,8.807302e+05,8.807325e+05,2.217727e+06

In [15]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1')
for k,v in gcdi_KPI_adequacy.loc[filter_,:].groupby(['day', 'µ', 'model_type']):
    print(v[['objective_value_uc','objective_value','day', 'µ', 'model_type','SOE_T_MWh']])

   objective_value_uc  objective_value  day    µ model_type    SOE_T_MWh
1       673344.851286    571018.903769    2  0.5   envelope  8168.973463
   objective_value_uc  objective_value  day    µ model_type    SOE_T_MWh
2       673344.851286    524846.774135    2  0.7   envelope  5915.818228
   objective_value_uc  objective_value  day    µ    model_type    SOE_T_MWh
0       673344.851286    463176.717185    2  1.0  conservative  2813.938396
   objective_value_uc  objective_value  day    µ model_type     SOE_T_MWh
0       673346.734391    408507.321975    2  1.0  e-reserve  8.821535e-12
   objective_value_uc  objective_value  day    µ model_type    SOE_T_MWh
5       570290.621895    530619.901346    3  0.5   envelope  5337.985470
2       570290.621900    530174.914631    3  0.5   envelope  5328.601168
   objective_value_uc  objective_value  day    µ model_type    SOE_T_MWh
3       570290.621895    465384.083933    3  0.7   envelope  2119.840198
0       570290.621895    458541.972428    3  0.7   envelope  1761.799316
   objective_value_uc  objective_value  day    µ    model_type     SOE_T_MWh
4       580563.560829    436283.821339    3  1.0  conservative  1.789483e-12
1       580563.560829    435479.056699    3  1.0  conservative  4.258925e-12
   objective_value_uc  objective_value  day    µ model_type     SOE_T_MWh
1       570293.677921    424132.904044    3  1.0  e-reserve -7.149587e-12
0       570293.677921    424132.904044    3  1.0  e-reserve -7.149587e-12

In [16]:
gcdi_KPI_adequacy.columns

Index(['model_type', 'solution_id', 'configuration', 'day', 'iteration',
       'LLD_h', 'ENS_MWh', 'input_load_MWh', 'CURD_h', 'CUR_MWh',
       'input_RES_production_MWh', 'thermal_production_MWh',
       'nonRES_nonThermal_production_MWh', 'storage_charge_MWh',
       'storage_discharge_MWh', 'storage_net_charge_MWh', 'SOE_T_MWh',
       'SOE_0_MWh', 'net_SOE_MWh', 'LGEN_MWh', 'production_cost', 'fixed_cost',
       'start_cost', 'LOL_cost', 'LGEN_cost', 'reserve_cost',
       'slack_reserve_up_cost', 'slack_reserve_down_cost', 'OPEX',
       'objective_value', 'production_cost_uc', 'fixed_cost_uc',
       'start_cost_uc', 'reserve_cost_uc', 'slack_reserve_up_cost_uc',
       'slack_reserve_down_cost_uc', 'OPEX_uc', 'objective_value_uc',
       'redispatch_cost', 'µ', 'avg_marginal_energy_price_MU_MWh',
       'avg_marginal_energy_price_uc_MU_MWh',
       'avg_marginal_reserve_up_price_uc_MU_MWh',
       'avg_marginal_reserve_down_price_uc_MU_MWh', 'input_load_uc_MWh',
       'reserve_up_uc_MWh', 'slack_reserve_up_uc_MWh', 'reserve_down_uc_MWh',
       'required_reserve_up_uc_MWh', 'required_reserve_down_uc_MWh',
       'slack_reserve_down_uc_MWh', 'energy_reserve_cost',
       'slack_energy_reserve_up_cost', 'slack_energy_reserve_down_cost',
       'energy_reserve_cost_uc', 'slack_energy_reserve_up_cost_uc',
       'slack_energy_reserve_down_cost_uc',
       'avg_marginal_energy_reserve_down_price_uc_MU_MWh',
       'avg_marginal_energy_reserve_up_price_uc_MU_MWh',
       'slack_energy_reserve_down_uc_MWh', 'required_energy_reserve_up_uc_MWh',
       'slack_energy_reserve_up_uc_MWh', 'required_energy_reserve_down_uc_MWh',
       'energy_reserve_down_uc_MWh', 'energy_reserve_up_uc_MWh'],
      dtype='object')