In [63]:
#lOAD PACKAGES
import pandas as pd
import matplotlib.pyplot as plt
import os
import plotly.express as px
# Import the processing module from the same folder
from processing import load_solutions, add_kwargs_as_indices, combine_solutions, read_parquet_and_convert, add_fields
# import processing 
# from pivottablejs import pivot_ui
G_save = True

In [64]:
ss = [
    {'solution_folder': f"RTS-GMLC_envelope_benchmark_s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_benchmark_v1.0s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_e_reserve_benchmark_s", 'model_type' : 'e-reserve'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.8s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.9s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.10s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.23s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v1.16.1s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v1.5s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_e_reserve_compare_v1.7s", 'model_type' : 'e-reserve'},
    # {'solution_folder': f"RTS-GMLC_e_reserve_compare_v1.9s", 'model_type' : 'e-reserve'},
    ]

s_uc = []
s_ed = []
gcd_KPI_adequacy = []
gcdi_KPI_adequacy = []
for sol in ss:
    # ρ = sol['ρ']
    s = sol['solution_folder']
    s_uc_name = 's_suc' if sol['model_type'] == 'stochastic' else 's_uc'
    # s_uc_ = load_solutions(s_uc_name, os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_ed_ = load_solutions("s_ed", os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_uc.append(s_uc_)
    # s_ed.append(s_ed_)

    gcd_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcd_KPI_adequacy.parquet"))
    gcd_KPI_adequacy_ = add_fields(gcd_KPI_adequacy_, model_type = sol['model_type'], solution_id = s) 

    gcdi_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcdi_KPI_adequacy.parquet"))
    gcdi_KPI_adequacy_ = add_fields(gcdi_KPI_adequacy_, model_type = sol['model_type'], solution_id = s)

    gcd_KPI_adequacy.append(gcd_KPI_adequacy_)
    gcdi_KPI_adequacy.append(gcdi_KPI_adequacy_)

# s_uc = combine_solutions(s_uc)
# s_ed = combine_solutions(s_ed)
gcd_KPI_adequacy = pd.concat(gcd_KPI_adequacy)
gcdi_KPI_adequacy = pd.concat(gcdi_KPI_adequacy)

if 'µ' in gcdi_KPI_adequacy.columns: 
#         # out['non-conservative'] = out[['model_type', 'µ']].apply(lambda x: (x[0] !='envelope') + (x[0] =='envelope')*(x[1]<1), axis = 1)
    gcdi_KPI_adequacy['model_type'] = gcdi_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)
    gcd_KPI_adequacy['model_type'] = gcd_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)

../output/RTS-GMLC_envelope_benchmark_s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_benchmark_s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.9s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.9s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.10s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.10s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.23s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.23s/all_gcdi_KPI_adequacy.parquet

In [65]:
gcd_KPI_adequacy

,model_type,solution_id,configuration,day,OV_uc,E_fixed_cost,E_storage_discharge_MWh,reserve_cost_uc,E_storage_charge_MWh,SOE_0_MWh,...,input_load_uc_MWh,CURE,ELGEN,EOPEX,slack_reserve_up_cost_uc,EENS,reserve_down_uc_MWh,E_input_load_MWh,OPEX_uc,µ
0,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,42411.584442,0.0,2.658124e-10,577492.018767,2.174425e-08,1.289566e-12,14812.458252,42409.966712,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11707.961617,0.029785,3226.496681,12683.7,...,42411.584442,0.0,3.640086e-10,473139.446044,6.366712e-09,1.122578e-12,14812.251179,42409.966712,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11477.471162,0.042446,5849.950564,12683.7,...,37815.376455,0.3,3.872743e-10,512433.607113,2.483200e-09,1.508531e-12,15960.658975,42025.234230,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13906.874641,0.042446,5221.718834,12683.7,...,37815.376455,0.3,1.163587e-09,458327.169219,8.559819e-09,3.550568e-12,15960.649370,42025.234230,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,42411.584442,0.0,0.000000e+00,577492.018767,2.174425e-08,0.000000e+00,14812.458252,42409.966712,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11707.995165,0.029785,3226.530229,12683.7,...,42411.584442,0.0,0.000000e+00,473139.446044,6.366712e-09,0.000000e+00,14812.251179,42409.966712,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11489.262384,0.042446,5861.741786,12683.7,...,37815.376455,0.3,0.000000e+00,512433.607115,2.483200e-09,0.000000e+00,15960.658975,42025.234230,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13951.640898,0.042446,5266.485090,12683.7,...,37815.376455,0.3,0.000000e+00,458327.169230,8.559819e-09,0.000000e+00,15960.649370,42025.234230,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,42411.584442,0.0,4.528816e-12,577492.018767,2.174425e-08,4.529422e-12,14812.458252,42409.966712,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11708.104658,0.029785,3226.639721,12683.7,...,42411.584442,0.0,2.169762e-12,473139.446044,6.366712e-09,2.169525e-12,14812.251179,42409.966712,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11488.206962,0.042446,5860.686364,12683.7,...,37815.376455,0.3,4.570339e-12,512433.607115,2.483200e-09,4.673548e-12,15960.658975,42025.234230,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13941.336786,0.042446,5256.180978,12683.7,...,37815.376455,0.3,1.134167e-11,458327.169227,8.559819e-09,1.133726e-11,15960.649370,42025.234230,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,42411.584442,0.0,1.295853e-15,571018.873984,2.174425e-08,1.296158e-15,14812.458252,42126.249053,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,42411.584442,0.0,1.376248e-12,463176.687400,6.366712e-09,1.376248e-12,14812.251179,42126.249053,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,37815.376456,0.0,4.803482e-16,530619.858898,2.483200e-09,4.803482e-16,15960.658975,43563.011255,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103865,0.042446,3624.646298,12683.7,...,37815.376456,0.0,5.937521e-16,436283.778893,8.559819e-09,5.937515e-16,15960.649370,43563.011255,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.23s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.821501,0.0,4586.384828,NaN,509.183052,12683.7,...,42411.584442,0.0,1.298672e-14,563521.291557,NaN,6.721403e-17,14812.458252,42126.249053,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.23s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.821500,0.0,9464.679579,NaN,509.183052,12683.7,...,42411.584442,0.0,3.087823e-13,450925.209354,NaN,1.615380e-15,14812.251179,42126.249053,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.23s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.579449,0.0,7252.179999,NaN,621.747913,12683.7,...,37815.376456,0.0,3.385144e-13,521251.318132,NaN,1.775820e-15,15960.658975,43563.011255,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.23s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.518382,0.0,12167.518500,NaN,621.747913,12683.7,...,37815.376456,0.0,2.761798e-10,407967.451596,NaN,1.441829e-12,15960.649370,43563.011255,580563.518382,1.0

In [66]:
values_ = ['reserve_cost_uc','slack_reserve_up_cost_uc','slack_reserve_down_cost_uc','energy_reserve_cost_uc','slack_energy_reserve_up_cost_uc','slack_energy_reserve_down_cost_uc']
values_ += [
    'reserve_up_uc_MWh', 'reserve_down_uc_MWh', 'slack_reserve_up_uc_MWh', 'slack_reserve_down_uc_MWh',
    'required_reserve_up_uc_MWh', 'required_reserve_down_uc_MWh',
    'energy_reserve_up_uc_MWh', 'energy_reserve_down_uc_MWh', 'slack_energy_reserve_up_uc_MWh', 'slack_energy_reserve_down_uc_MWh',
    'required_energy_reserve_up_uc_MWh', 'required_energy_reserve_down_uc_MWh'
]
values_ += ['EOV',]
values_ = [v for v in values_ if v in gcd_KPI_adequacy.columns]
pivot = pd.pivot_table(
    gcd_KPI_adequacy,
    index=['day', 'solution_id'],
    columns='model_type',
    values=values_
)
print(pivot)    
# pivot

                                                EOV                 \
model_type                             conservative       envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s     473139.475829  577492.048552
    RTS-GMLC_envelope_compare_v1.10s  463176.717185  571018.903769
    RTS-GMLC_envelope_compare_v1.23s  450925.209354  563521.291557
    RTS-GMLC_envelope_compare_v1.8s   473139.475829  577492.048552
    RTS-GMLC_envelope_compare_v1.9s   473139.475829  577492.048552
3   RTS-GMLC_envelope_benchmark_s     458327.211666  512433.649559
    RTS-GMLC_envelope_compare_v1.10s  436283.821339  530619.901345
    RTS-GMLC_envelope_compare_v1.23s  407967.451596  521251.318132
    RTS-GMLC_envelope_compare_v1.8s   458327.211676  512433.649561
    RTS-GMLC_envelope_compare_v1.9s   458327.211673  512433.649561

                                     required_reserve_down_uc_MWh  \
model_type                                           conservative
day solution_id
2   RTS-GMLC_envelope_benchmark_s                    14812.233953
    RTS-GMLC_envelope_compare_v1.10s                 14812.233953
    RTS-GMLC_envelope_compare_v1.23s                 14812.233953
    RTS-GMLC_envelope_compare_v1.8s                  14812.233953
    RTS-GMLC_envelope_compare_v1.9s                  14812.233953
3   RTS-GMLC_envelope_benchmark_s                    15960.645167
    RTS-GMLC_envelope_compare_v1.10s                 15960.645167
    RTS-GMLC_envelope_compare_v1.23s                 15960.645167
    RTS-GMLC_envelope_compare_v1.8s                  15960.645167
    RTS-GMLC_envelope_compare_v1.9s                  15960.645167

                                                   required_reserve_up_uc_MWh  \
model_type                                envelope               conservative
day solution_id
2   RTS-GMLC_envelope_benchmark_s     14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.10s  14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.23s  14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.8s   14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.9s   14812.233953               14972.695060
3   RTS-GMLC_envelope_benchmark_s     15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.10s  15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.23s  15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.8s   15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.9s   15960.645167               26485.519376

                                                   reserve_cost_uc            \
model_type                                envelope    conservative  envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s     14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.10s  14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.23s  14972.695060             NaN       NaN
    RTS-GMLC_envelope_compare_v1.8s   14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.9s   14972.695060        0.029785  0.029785
3   RTS-GMLC_envelope_benchmark_s     26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.10s  26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.23s  26485.519376             NaN       NaN
    RTS-GMLC_envelope_compare_v1.8s   26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.9s   26485.519376        0.042446  0.042446

                                     reserve_down_uc_MWh                \
model_type                                  conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s           14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.10s        14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.23s        14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.8s         14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.9s         14812.251179  14812.458252
3   RTS-GMLC_envelope_benchmark_s           15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.10s        15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.23s        15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.8s         15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.9s         15960.649370  15960.658975

                                     reserve_up_uc_MWh                \
model_type                                conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s         14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.10s      14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.23s      14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.8s       14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.9s       14972.709270  14972.719902
3   RTS-GMLC_envelope_benchmark_s         26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.10s      26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.23s      26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.8s       26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.9s       26485.578429  26485.538745

                                     slack_reserve_down_cost_uc                \
model_type                                         conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s                  6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.10s               6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.23s                        NaN           NaN
    RTS-GMLC_envelope_compare_v1.8s                6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.9s                6.366712e-09  2.174425e-08
3   RTS-GMLC_envelope_benchmark_s                  9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.10s               9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.23s                        NaN           NaN
    RTS-GMLC_envelope_compare_v1.8s                9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.9s                9.083310e-09  2.483200e-09

                                     slack_reserve_down_uc_MWh                \
model_type                                        conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s                 2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.10s              2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.23s              2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s               2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.9s               2.546685e-11  8.697700e-11
3   RTS-GMLC_envelope_benchmark_s                 3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.10s              3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.23s              3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s               3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.9s               3.633324e-11  9.932801e-12

                                     slack_reserve_up_cost_uc                \
model_type                                       conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s                6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.10s             6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.23s                      NaN           NaN
    RTS-GMLC_envelope_compare_v1.8s              6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.9s              6.366712e-09  2.174425e-08
3   RTS-GMLC_envelope_benchmark_s                8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.10s             8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.23s                      NaN           NaN
    RTS-GMLC_envelope_compare_v1.8s              8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.9s              8.559819e-09  2.483200e-09

                                     slack_reserve_up_uc_MWh
model_type                                      conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s               2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.10s            2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.23s            2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s             2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.9s             2.546685e-11  8.697700e-11
3   RTS-GMLC_envelope_benchmark_s               3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.10s            3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.23s            3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s             3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.9s             3.423928e-11  9.932801e-12

In [67]:
values_

['reserve_cost_uc',
 'slack_reserve_up_cost_uc',
 'slack_reserve_down_cost_uc',
 'reserve_up_uc_MWh',
 'reserve_down_uc_MWh',
 'slack_reserve_up_uc_MWh',
 'slack_reserve_down_uc_MWh',
 'required_reserve_up_uc_MWh',
 'required_reserve_down_uc_MWh',
 'EOV']

In [68]:
# pivot.to_csv('pivot.csv')
# gcd_KPI_adequacy.to_csv('test.csv')
#

In [79]:
from itertools import product

days = [2]
scalar = []
for sol, day in product(ss, days):
    s = sol['solution_folder']
    scalar_ = pd.read_parquet(os.path.join("..", "output", s, f'n_{day}','s_uc_scalar.parquet'))
    scalar_['day'] = day
    scalar_['solution_id'] = sol['solution_folder']
    # scalar_.model_type = sol['model_type']
    scalar.append(scalar_)        

scalar = pd.concat(scalar)

In [80]:
scalar

,objective_value,termination_status,OPEX,day,configuration,solution_id
0,673344.851285,OPTIMAL,673344.821500,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
1,673344.851286,OPTIMAL,673344.821501,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_benchmark_s
0,673344.851285,OPTIMAL,673344.821500,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.8s
1,673344.851286,OPTIMAL,673344.821501,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.8s
0,673344.851285,OPTIMAL,673344.821500,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.9s
1,673344.851286,OPTIMAL,673344.821501,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.9s
0,673344.851285,OPTIMAL,673344.821500,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.10s
1,673344.851286,OPTIMAL,673344.821501,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.10s
0,673344.851285,OPTIMAL,673344.821500,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.23s
1,673344.851286,OPTIMAL,673344.821501,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.23s

In [71]:
gcdi_KPI_adequacy.columns

Index(['model_type', 'solution_id', 'configuration', 'day', 'iteration',
       'LLD_h', 'ENS_MWh', 'input_load_MWh', 'CURD_h', 'CUR_MWh',
       'input_RES_production_MWh', 'thermal_production_MWh',
       'nonRES_nonThermal_production_MWh', 'storage_charge_MWh',
       'storage_discharge_MWh', 'storage_net_charge_MWh', 'SOE_T_MWh',
       'SOE_0_MWh', 'net_SOE_MWh', 'LGEN_MWh', 'production_cost', 'fixed_cost',
       'start_cost', 'LOL_cost', 'LGEN_cost', 'reserve_cost',
       'slack_reserve_up_cost', 'slack_reserve_down_cost', 'OPEX',
       'objective_value', 'production_cost_uc', 'fixed_cost_uc',
       'start_cost_uc', 'reserve_cost_uc', 'slack_reserve_up_cost_uc',
       'slack_reserve_down_cost_uc', 'OPEX_uc', 'objective_value_uc',
       'redispatch_cost', 'µ', 'avg_marginal_energy_price_MU_MWh',
       'avg_marginal_energy_price_uc_MU_MWh',
       'avg_marginal_reserve_up_price_uc_MU_MWh',
       'avg_marginal_reserve_down_price_uc_MU_MWh', 'input_load_uc_MWh',
       'reserve_up_uc_MWh', 'slack_reserve_up_uc_MWh', 'reserve_down_uc_MWh',
       'required_reserve_up_uc_MWh', 'required_reserve_down_uc_MWh',
       'slack_reserve_down_uc_MWh'],
      dtype='object')

In [ ]:
gcdi_KPI_adequacy['OV_reserve'] = gcdi_KPI_adequacy.objective_value - gcdi_KPI_adequacy.reserve_cost_uc

In [ ]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') #&  (gcdi_KPI_adequacy.day == 3)
for k,v in gcdi_KPI_adequacy.loc[filter_,:].groupby(['day', 'µ', 'model_type']):
    print(v[['objective_value_uc','objective_value', 'OV_reserve', 'day', 'µ', 'model_type']])

     objective_value_uc  objective_value  day    µ model_type
165       673344.851286    571018.903769    2  0.5   envelope
165       673344.851286    571018.903769    2  0.5   envelope
165       673344.851286    571018.903769    2  0.5   envelope
1         673344.851286    571018.903769    2  0.5   envelope
1         673344.821501    563521.291557    2  0.5   envelope
    objective_value_uc  objective_value  day    µ    model_type
65       673344.851285    463176.717185    2  1.0  conservative
65       673344.851285    463176.717185    2  1.0  conservative
65       673344.851285    463176.717185    2  1.0  conservative
0        673344.851285    463176.717185    2  1.0  conservative
0        673344.821500    450925.209354    2  1.0  conservative
     objective_value_uc  objective_value  day    µ model_type
365       570290.621895    530619.901346    3  0.5   envelope
365       570290.621895    530619.901345    3  0.5   envelope
365       570290.621895    530619.901345    3  0.5   envelope
3         570290.621895    530619.901345    3  0.5   envelope
3         570290.579449    521251.318132    3  0.5   envelope
     objective_value_uc  objective_value  day    µ    model_type
265       580563.560828    436283.821340    3  1.0  conservative
265       580563.560828    436283.821342    3  1.0  conservative
265       580563.560828    436283.821339    3  1.0  conservative
2         580563.560828    436283.821339    3  1.0  conservative
2         580563.518382    407967.451596    3  1.0  conservative

In [74]:
gcdi_KPI_adequacy[['objective_value_uc','objective_value','solution_id', 'day', 'µ', 'model_type']]

,objective_value_uc,objective_value,solution_id,day,µ,model_type
0,673344.851285,450946.521613,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
1,673344.851285,390804.266707,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
2,673344.851285,478871.229947,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
3,673344.851285,549114.153620,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
4,673344.851285,393903.636144,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
...,...,...,...,...,...,...
3,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.10s,3,0.5,envelope
0,673344.821500,450925.209354,RTS-GMLC_envelope_compare_v1.23s,2,1.0,conservative
1,673344.821501,563521.291557,RTS-GMLC_envelope_compare_v1.23s,2,0.5,envelope
2,580563.518382,407967.451596,RTS-GMLC_envelope_compare_v1.23s,3,1.0,conservative
3,570290.579449,521251.318132,RTS-GMLC_envelope_compare_v1.23s,3,0.5,envelope

In [75]:
x = 436283.821342
y = 436283.821339
print( (x-y)/y)

6.876176674651827e-12