In [35]:
#lOAD PACKAGES
import pandas as pd
import matplotlib.pyplot as plt
import os
import plotly.express as px
# Import the processing module from the same folder
from processing import load_solutions, add_kwargs_as_indices, combine_solutions, read_parquet_and_convert, add_fields
# import processing 
# from pivottablejs import pivot_ui
G_save = True

In [36]:
ss = [
    {'solution_folder': f"RTS-GMLC_envelope_benchmark_s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_e_reserve_benchmark_s", 'model_type' : 'e-reserve'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v0.5s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.8s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v1.5s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_e_reserve_compare_v1.7s", 'model_type' : 'e-reserve'},
    ]

s_uc = []
s_ed = []
gcd_KPI_adequacy = []
gcdi_KPI_adequacy = []
for sol in ss:
    # ρ = sol['ρ']
    s = sol['solution_folder']
    s_uc_name = 's_suc' if sol['model_type'] == 'stochastic' else 's_uc'
    # s_uc_ = load_solutions(s_uc_name, os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_ed_ = load_solutions("s_ed", os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_uc.append(s_uc_)
    # s_ed.append(s_ed_)

    gcd_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcd_KPI_adequacy.parquet"))
    gcd_KPI_adequacy_ = add_fields(gcd_KPI_adequacy_, model_type = sol['model_type'], solution_id = s) 

    gcdi_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcdi_KPI_adequacy.parquet"))
    gcdi_KPI_adequacy_ = add_fields(gcdi_KPI_adequacy_, model_type = sol['model_type'], solution_id = s)

    gcd_KPI_adequacy.append(gcd_KPI_adequacy_)
    gcdi_KPI_adequacy.append(gcdi_KPI_adequacy_)

# s_uc = combine_solutions(s_uc)
# s_ed = combine_solutions(s_ed)
gcd_KPI_adequacy = pd.concat(gcd_KPI_adequacy)
gcdi_KPI_adequacy = pd.concat(gcdi_KPI_adequacy)

if 'µ' in gcdi_KPI_adequacy.columns: 
#         # out['non-conservative'] = out[['model_type', 'µ']].apply(lambda x: (x[0] !='envelope') + (x[0] =='envelope')*(x[1]<1), axis = 1)
    gcdi_KPI_adequacy['model_type'] = gcdi_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)
    gcd_KPI_adequacy['model_type'] = gcd_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)

../output/RTS-GMLC_envelope_benchmark_s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_benchmark_s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_benchmark_s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_benchmark_s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_compare_v1.7s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_e_reserve_compare_v1.7s/all_gcdi_KPI_adequacy.parquet

In [37]:
gcd_KPI_adequacy

,model_type,solution_id,configuration,day,OV_uc,E_fixed_cost,E_storage_discharge_MWh,reserve_cost_uc,E_storage_charge_MWh,SOE_0_MWh,...,slack_energy_reserve_down_cost_uc,required_energy_reserve_down_uc_MWh,required_energy_reserve_up_uc_MWh,slack_energy_reserve_down_uc_MWh,slack_energy_reserve_up_cost_uc,avg_marginal_energy_reserve_down_price_uc_MU_MWh,energy_reserve_down_uc_MWh,energy_reserve_cost_uc,avg_marginal_energy_reserve_up_price_uc_MU_MWh,energy_reserve_up_uc_MWh
0,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103865,0.042446,3624.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,673346.729452,0.0,14532.956333,NaN,3349.291564,12683.7,...,0.000057,1.017636e+06,8.876647e+05,2.282002e-07,0.000057,None,1.017982e+06,1.906243,None,8.882609e+05
1,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,570293.677990,0.0,15066.559235,NaN,3894.646298,12683.7,...,0.000003,8.807302e+05,2.217726e+06,1.314965e-08,0.000003,None,8.807319e+05,3.098460,None,2.217728e+06
0,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103866,0.042446,3624.646298,12683.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673346.727052,0.0,13756.044137,NaN,3349.291564,12683.7,...,0.000017,1.017636e+06,8.876647e+05,6.806620e-08,0.000017,None,1.017666e+06,1.905373,None,8.877079e+05
1,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_1_dn_1,2,673346.729452,0.0,14532.956333,NaN,3349.291564,12683.7,...,0.000057,1.017636e+06,8.876647e+05,2.282002e-07,0.000057,None,1.017982e+06,1.906243,None,8.882609e+05
2,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570293.678281,0.0,15066.559235,NaN,3894.646298,12683.7,...,0.000006,8.807302e+05,2.217726e+06,2.434966e-08,0.000006,None,8.807641e+05,3.098533,None,2.217768e+06
3,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_1_dn_1,3,570293.677990,0.0,15066.559235,NaN,3894.646298,12683.7,...,0.000003,8.807302e+05,2.217726e+06,1.314965e-08,0.000003,None,8.807319e+05,3.098460,None,2.217728e+06

In [38]:
values_ = ['reserve_cost_uc','slack_reserve_up_cost_uc','slack_reserve_down_cost_uc','energy_reserve_cost_uc','slack_energy_reserve_up_cost_uc','slack_energy_reserve_down_cost_uc']
values_ += [
    'reserve_up_uc_MWh', 'reserve_down_uc_MWh', 'slack_reserve_up_uc_MWh', 'slack_reserve_down_uc_MWh',
    'required_reserve_up_uc_MWh', 'required_reserve_down_uc_MWh',
    'energy_reserve_up_uc_MWh', 'energy_reserve_down_uc_MWh', 'slack_energy_reserve_up_uc_MWh', 'slack_energy_reserve_down_uc_MWh',
    'required_energy_reserve_up_uc_MWh', 'required_energy_reserve_down_uc_MWh'
]
values_ += ['EOV',]
values_ = [v for v in values_ if v in gcd_KPI_adequacy.columns]
pivot = pd.pivot_table(
    gcd_KPI_adequacy,
    index=['day', 'solution_id'],
    columns='model_type',
    values=values_
)
print(pivot)    
# pivot

                                                EOV                 \
model_type                             conservative      e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s              NaN  409516.584938
    RTS-GMLC_e_reserve_compare_v1.7s            NaN  417677.206749
    RTS-GMLC_envelope_benchmark_s     463176.717185            NaN
    RTS-GMLC_envelope_compare_v1.8s   463176.717185            NaN
3   RTS-GMLC_e_reserve_benchmark_s              NaN  424132.904044
    RTS-GMLC_e_reserve_compare_v1.7s            NaN  424132.904044
    RTS-GMLC_envelope_benchmark_s     436283.821340            NaN
    RTS-GMLC_envelope_compare_v1.8s   436283.821342            NaN

                                                    energy_reserve_cost_uc  \
model_type                                 envelope              e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s              NaN               1.906243
    RTS-GMLC_e_reserve_compare_v1.7s            NaN               1.905808
    RTS-GMLC_envelope_benchmark_s     571018.903769                    NaN
    RTS-GMLC_envelope_compare_v1.8s   571018.903769                    NaN
3   RTS-GMLC_e_reserve_benchmark_s              NaN               3.098460
    RTS-GMLC_e_reserve_compare_v1.7s            NaN               3.098496
    RTS-GMLC_envelope_benchmark_s     530619.901346                    NaN
    RTS-GMLC_envelope_compare_v1.8s   530619.901345                    NaN

                                     energy_reserve_down_uc_MWh  \
model_type                                            e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                 1.017982e+06
    RTS-GMLC_e_reserve_compare_v1.7s               1.017824e+06
    RTS-GMLC_envelope_benchmark_s                           NaN
    RTS-GMLC_envelope_compare_v1.8s                         NaN
3   RTS-GMLC_e_reserve_benchmark_s                 8.807319e+05
    RTS-GMLC_e_reserve_compare_v1.7s               8.807480e+05
    RTS-GMLC_envelope_benchmark_s                           NaN
    RTS-GMLC_envelope_compare_v1.8s                         NaN

                                     energy_reserve_up_uc_MWh  \
model_type                                          e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s               8.882609e+05
    RTS-GMLC_e_reserve_compare_v1.7s             8.879844e+05
    RTS-GMLC_envelope_benchmark_s                         NaN
    RTS-GMLC_envelope_compare_v1.8s                       NaN
3   RTS-GMLC_e_reserve_benchmark_s               2.217728e+06
    RTS-GMLC_e_reserve_compare_v1.7s             2.217748e+06
    RTS-GMLC_envelope_benchmark_s                         NaN
    RTS-GMLC_envelope_compare_v1.8s                       NaN

                                     required_energy_reserve_down_uc_MWh  \
model_type                                                     e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                          1.017636e+06
    RTS-GMLC_e_reserve_compare_v1.7s                        1.017636e+06
    RTS-GMLC_envelope_benchmark_s                                    NaN
    RTS-GMLC_envelope_compare_v1.8s                                  NaN
3   RTS-GMLC_e_reserve_benchmark_s                          8.807302e+05
    RTS-GMLC_e_reserve_compare_v1.7s                        8.807302e+05
    RTS-GMLC_envelope_benchmark_s                                    NaN
    RTS-GMLC_envelope_compare_v1.8s                                  NaN

                                     required_energy_reserve_up_uc_MWh  \
model_type                                                   e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                        8.876647e+05
    RTS-GMLC_e_reserve_compare_v1.7s                      8.876647e+05
    RTS-GMLC_envelope_benchmark_s                                  NaN
    RTS-GMLC_envelope_compare_v1.8s                                NaN
3   RTS-GMLC_e_reserve_benchmark_s                        2.217726e+06
    RTS-GMLC_e_reserve_compare_v1.7s                      2.217726e+06
    RTS-GMLC_envelope_benchmark_s                                  NaN
    RTS-GMLC_envelope_compare_v1.8s                                NaN

                                     required_reserve_down_uc_MWh  \
model_type                                           conservative
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                            NaN
    RTS-GMLC_e_reserve_compare_v1.7s                          NaN
    RTS-GMLC_envelope_benchmark_s                    14812.233953
    RTS-GMLC_envelope_compare_v1.8s                  14812.233953
3   RTS-GMLC_e_reserve_benchmark_s                            NaN
    RTS-GMLC_e_reserve_compare_v1.7s                          NaN
    RTS-GMLC_envelope_benchmark_s                    15960.645167
    RTS-GMLC_envelope_compare_v1.8s                  15960.645167

                                                    ...  \
model_type                                envelope  ...
day solution_id                                     ...
2   RTS-GMLC_e_reserve_benchmark_s             NaN  ...
    RTS-GMLC_e_reserve_compare_v1.7s           NaN  ...
    RTS-GMLC_envelope_benchmark_s     14812.233953  ...
    RTS-GMLC_envelope_compare_v1.8s   14812.233953  ...
3   RTS-GMLC_e_reserve_benchmark_s             NaN  ...
    RTS-GMLC_e_reserve_compare_v1.7s           NaN  ...
    RTS-GMLC_envelope_benchmark_s     15960.645167  ...
    RTS-GMLC_envelope_compare_v1.8s   15960.645167  ...

                                     slack_energy_reserve_up_cost_uc  \
model_type                                                 e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                          0.000057
    RTS-GMLC_e_reserve_compare_v1.7s                        0.000037
    RTS-GMLC_envelope_benchmark_s                                NaN
    RTS-GMLC_envelope_compare_v1.8s                              NaN
3   RTS-GMLC_e_reserve_benchmark_s                          0.000003
    RTS-GMLC_e_reserve_compare_v1.7s                        0.000004
    RTS-GMLC_envelope_benchmark_s                                NaN
    RTS-GMLC_envelope_compare_v1.8s                              NaN

                                     slack_energy_reserve_up_uc_MWh  \
model_type                                                e-reserve
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                     2.280915e-07
    RTS-GMLC_e_reserve_compare_v1.7s                   1.480726e-07
    RTS-GMLC_envelope_benchmark_s                               NaN
    RTS-GMLC_envelope_compare_v1.8s                             NaN
3   RTS-GMLC_e_reserve_benchmark_s                     1.080309e-08
    RTS-GMLC_e_reserve_compare_v1.7s                   1.671302e-08
    RTS-GMLC_envelope_benchmark_s                               NaN
    RTS-GMLC_envelope_compare_v1.8s                             NaN

                                     slack_reserve_down_cost_uc                \
model_type                                         conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                          NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                        NaN           NaN
    RTS-GMLC_envelope_benchmark_s                  6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.8s                6.366712e-09  2.174425e-08
3   RTS-GMLC_e_reserve_benchmark_s                          NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                        NaN           NaN
    RTS-GMLC_envelope_benchmark_s                  9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.8s                9.083310e-09  2.483200e-09

                                     slack_reserve_down_uc_MWh                \
model_type                                        conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                         NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                       NaN           NaN
    RTS-GMLC_envelope_benchmark_s                 2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s               2.546685e-11  8.697700e-11
3   RTS-GMLC_e_reserve_benchmark_s                         NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                       NaN           NaN
    RTS-GMLC_envelope_benchmark_s                 3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s               3.633324e-11  9.932801e-12

                                     slack_reserve_up_cost_uc                \
model_type                                       conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                        NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                      NaN           NaN
    RTS-GMLC_envelope_benchmark_s                6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.8s              6.366712e-09  2.174425e-08
3   RTS-GMLC_e_reserve_benchmark_s                        NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                      NaN           NaN
    RTS-GMLC_envelope_benchmark_s                8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.8s              8.559819e-09  2.483200e-09

                                     slack_reserve_up_uc_MWh
model_type                                      conservative      envelope
day solution_id
2   RTS-GMLC_e_reserve_benchmark_s                       NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                     NaN           NaN
    RTS-GMLC_envelope_benchmark_s               2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s             2.546685e-11  8.697700e-11
3   RTS-GMLC_e_reserve_benchmark_s                       NaN           NaN
    RTS-GMLC_e_reserve_compare_v1.7s                     NaN           NaN
    RTS-GMLC_envelope_benchmark_s               3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s             3.423928e-11  9.932801e-12

[8 rows x 30 columns]

In [39]:
values_

['reserve_cost_uc',
 'slack_reserve_up_cost_uc',
 'slack_reserve_down_cost_uc',
 'energy_reserve_cost_uc',
 'slack_energy_reserve_up_cost_uc',
 'slack_energy_reserve_down_cost_uc',
 'reserve_up_uc_MWh',
 'reserve_down_uc_MWh',
 'slack_reserve_up_uc_MWh',
 'slack_reserve_down_uc_MWh',
 'required_reserve_up_uc_MWh',
 'required_reserve_down_uc_MWh',
 'energy_reserve_up_uc_MWh',
 'energy_reserve_down_uc_MWh',
 'slack_energy_reserve_up_uc_MWh',
 'slack_energy_reserve_down_uc_MWh',
 'required_energy_reserve_up_uc_MWh',
 'required_energy_reserve_down_uc_MWh',
 'EOV']

In [40]:
# pivot.to_csv('pivot.csv')
# gcd_KPI_adequacy.to_csv('test.csv')
#

In [41]:
from itertools import product

days = [3]
scalar = []
for sol, day in product(ss, days):
    s = sol['solution_folder']
    scalar_ = pd.read_parquet(os.path.join("..", "output", s, f'n_{day}','s_uc_scalar.parquet'))
    scalar_['day'] = day
    scalar_['solution_id'] = sol['solution_folder']
    # scalar_.model_type = sol['model_type']
    scalar.append(scalar_)        

scalar = pd.concat(scalar)

In [42]:
# scalar.to_csv('scalar.csv', index=False)

In [43]:
scalar

,objective_value,termination_status,OPEX,day,configuration,solution_id
0,580563.560828,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
1,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_benchmark_s
0,570293.677990,OPTIMAL,570290.579524,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_e_reserve_benchmark_s
0,580563.560828,OPTIMAL,580563.518382,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.8s
1,570290.621895,OPTIMAL,570290.579449,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.8s
0,570293.677990,OPTIMAL,570290.579524,3,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_e_reserve_compare_v1.7s
1,570293.678281,OPTIMAL,570290.579737,3,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_e_reserve_compare_v1.7s

In [44]:
gcdi_KPI_adequacy['µ']

0    1.0
1    0.5
2    1.0
3    0.5
0    1.0
1    1.0
0    1.0
1    0.5
2    1.0
3    0.5
0    1.0
1    0.5
2    1.0
3    0.5
Name: µ, dtype: float64

In [45]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy.model_type == 'conservative')  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
2,580563.560828,436283.821340,RTS-GMLC_envelope_benchmark_s,demand_1
2,580563.560828,436283.821342,RTS-GMLC_envelope_compare_v1.8s,demand_1

In [46]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy['µ'] == 0.5)  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
3,570290.621895,530619.901346,RTS-GMLC_envelope_benchmark_s,demand_1
3,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.8s,demand_1
3,570293.678281,424132.904044,RTS-GMLC_e_reserve_compare_v1.7s,demand_1

In [47]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') & (gcdi_KPI_adequacy.model_type == 'e-reserve')  & (gcdi_KPI_adequacy.day == 3)
aux = gcdi_KPI_adequacy.loc[filter_,:]
aux[['objective_value_uc','objective_value','solution_id','iteration']]

,objective_value_uc,objective_value,solution_id,iteration
1,570293.677990,424132.904044,RTS-GMLC_e_reserve_benchmark_s,demand_1
2,570293.677990,424132.904044,RTS-GMLC_e_reserve_compare_v1.7s,demand_1
3,570293.678281,424132.904044,RTS-GMLC_e_reserve_compare_v1.7s,demand_1

In [48]:
gcdi_KPI_adequacy

,model_type,solution_id,configuration,day,iteration,LLD_h,ENS_MWh,input_load_MWh,CURD_h,CUR_MWh,...,slack_energy_reserve_up_cost_uc,slack_energy_reserve_down_cost_uc,avg_marginal_energy_reserve_down_price_uc_MU_MWh,avg_marginal_energy_reserve_up_price_uc_MU_MWh,slack_energy_reserve_down_uc_MWh,required_energy_reserve_up_uc_MWh,slack_energy_reserve_up_uc_MWh,required_energy_reserve_down_uc_MWh,energy_reserve_down_uc_MWh,energy_reserve_up_uc_MWh
0,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,1.673074e-14,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,1.517342e-14,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,1.907158e-12,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,demand_1,0,6.376472e-12,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,3.463193e-13,42126.249053,0,0.0,...,0.000057,0.000057,None,None,2.282002e-07,8.876647e+05,2.280915e-07,1.017636e+06,1.017982e+06,8.882609e+05
1,e-reserve,RTS-GMLC_e_reserve_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,6.075695e-16,43563.011255,0,0.0,...,0.000003,0.000003,None,None,1.314965e-08,2.217726e+06,1.080309e-08,8.807302e+05,8.807319e+05,2.217728e+06
0,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,0.000000e+00,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,0.000000e+00,42126.249053,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,0.000000e+00,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,demand_1,0,0.000000e+00,43563.011255,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,3.463193e-13,42126.249053,0,0.0,...,0.000057,0.000057,None,None,2.282002e-07,8.876647e+05,2.280915e-07,1.017636e+06,1.017982e+06,8.882609e+05
1,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,6.762529e-14,42126.249053,0,0.0,...,0.000017,0.000017,None,None,6.806620e-08,8.876647e+05,6.805376e-08,1.017636e+06,1.017666e+06,8.877079e+05
2,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_1_dn_1,3,demand_1,0,6.075695e-16,43563.011255,0,0.0,...,0.000003,0.000003,None,None,1.314965e-08,2.217726e+06,1.080309e-08,8.807302e+05,8.807319e+05,2.217728e+06
3,e-reserve,RTS-GMLC_e_reserve_compare_v1.7s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,demand_1,0,5.812794e-13,43563.011255,0,0.0,...,0.000006,0.000006,None,None,2.434966e-08,2.217726e+06,2.262295e-08,8.807302e+05,8.807641e+05,2.217768e+06

In [49]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') #&  (gcdi_KPI_adequacy.day == 3)
for k,v in gcdi_KPI_adequacy.loc[filter_,:].groupby(['day', 'µ', 'model_type']):
    print(v[['objective_value_uc','objective_value', 'day', 'µ', 'model_type', 'SOE_T_MWh']])

   objective_value_uc  objective_value  day    µ model_type   SOE_T_MWh
1       673346.727052    425837.828561    2  0.5  e-reserve  906.645654
   objective_value_uc  objective_value  day    µ model_type    SOE_T_MWh
1       673344.851286    571018.903769    2  0.5   envelope  8168.973463
1       673344.851286    571018.903769    2  0.5   envelope  8168.973463
   objective_value_uc  objective_value  day    µ    model_type    SOE_T_MWh
0       673344.851285    463176.717185    2  1.0  conservative  2813.938396
0       673344.851285    463176.717185    2  1.0  conservative  2813.938396
   objective_value_uc  objective_value  day    µ model_type  SOE_T_MWh
0       673346.729452    409516.584938    2  1.0  e-reserve  51.154903
0       673346.729452    409516.584938    2  1.0  e-reserve  51.154903
   objective_value_uc  objective_value  day    µ model_type     SOE_T_MWh
3       570293.678281    424132.904044    3  0.5  e-reserve  1.293039e-10
   objective_value_uc  objective_value  day    µ model_type   SOE_T_MWh
3       570290.621895    530619.901346    3  0.5   envelope  5337.98547
3       570290.621895    530619.901345    3  0.5   envelope  5337.98547
   objective_value_uc  objective_value  day    µ    model_type     SOE_T_MWh
2       580563.560828    436283.821340    3  1.0  conservative  4.118780e-10
2       580563.560828    436283.821342    3  1.0  conservative  3.880825e-09
   objective_value_uc  objective_value  day    µ model_type     SOE_T_MWh
1        570293.67799    424132.904044    3  1.0  e-reserve -7.133918e-12
2        570293.67799    424132.904044    3  1.0  e-reserve -7.133918e-12

In [50]:
gcdi_KPI_adequacy[['objective_value_uc','objective_value','solution_id', 'day', 'µ', 'model_type']]

,objective_value_uc,objective_value,solution_id,day,µ,model_type
0,673344.851285,463176.717185,RTS-GMLC_envelope_benchmark_s,2,1.0,conservative
1,673344.851286,571018.903769,RTS-GMLC_envelope_benchmark_s,2,0.5,envelope
2,580563.560828,436283.821340,RTS-GMLC_envelope_benchmark_s,3,1.0,conservative
3,570290.621895,530619.901346,RTS-GMLC_envelope_benchmark_s,3,0.5,envelope
0,673346.729452,409516.584938,RTS-GMLC_e_reserve_benchmark_s,2,1.0,e-reserve
1,570293.677990,424132.904044,RTS-GMLC_e_reserve_benchmark_s,3,1.0,e-reserve
0,673344.851285,463176.717185,RTS-GMLC_envelope_compare_v1.8s,2,1.0,conservative
1,673344.851286,571018.903769,RTS-GMLC_envelope_compare_v1.8s,2,0.5,envelope
2,580563.560828,436283.821342,RTS-GMLC_envelope_compare_v1.8s,3,1.0,conservative
3,570290.621895,530619.901345,RTS-GMLC_envelope_compare_v1.8s,3,0.5,envelope
0,673346.729452,409516.584938,RTS-GMLC_e_reserve_compare_v1.7s,2,1.0,e-reserve
1,673346.727052,425837.828561,RTS-GMLC_e_reserve_compare_v1.7s,2,0.5,e-reserve
2,570293.677990,424132.904044,RTS-GMLC_e_reserve_compare_v1.7s,3,1.0,e-reserve
3,570293.678281,424132.904044,RTS-GMLC_e_reserve_compare_v1.7s,3,0.5,e-reserve

In [52]:
 (436283.821340 -  436283.821342)/ 436283.821342

-4.58407331074987e-12