In [1]:
#lOAD PACKAGES
import pandas as pd
import matplotlib.pyplot as plt
import os
import plotly.express as px
# Import the processing module from the same folder
from processing import load_solutions, add_kwargs_as_indices, combine_solutions, read_parquet_and_convert, add_fields
# import processing 
# from pivottablejs import pivot_ui
G_save = True

In [ ]:
ss = [
    {'solution_folder': f"RTS-GMLC_envelope_benchmark_s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_benchmark_v1.0s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_e_reserve_benchmark_s", 'model_type' : 'e-reserve'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.8s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.9s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.10s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.22s", 'model_type' : 'envelope'},
    {'solution_folder': f"RTS-GMLC_envelope_compare_v1.24s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v1.16.1s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_envelope_compare_v1.5s", 'model_type' : 'envelope'},
    # {'solution_folder': f"RTS-GMLC_e_reserve_compare_v1.7s", 'model_type' : 'e-reserve'},
    # {'solution_folder': f"RTS-GMLC_e_reserve_compare_v1.9s", 'model_type' : 'e-reserve'},
    ]

s_uc = []
s_ed = []
gcd_KPI_adequacy = []
gcdi_KPI_adequacy = []
for sol in ss:
    # ρ = sol['ρ']
    s = sol['solution_folder']
    s_uc_name = 's_suc' if sol['model_type'] == 'stochastic' else 's_uc'
    # s_uc_ = load_solutions(s_uc_name, os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_ed_ = load_solutions("s_ed", os.path.join("..", "output", s), [7], model_type = sol['model_type'], ρ=ρ, solution_id = s)
    # s_uc.append(s_uc_)
    # s_ed.append(s_ed_)

    gcd_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcd_KPI_adequacy.parquet"))
    gcd_KPI_adequacy_ = add_fields(gcd_KPI_adequacy_, model_type = sol['model_type'], solution_id = s) 

    gcdi_KPI_adequacy_ = read_parquet_and_convert( os.path.join("..", "output", s, "all_gcdi_KPI_adequacy.parquet"))
    gcdi_KPI_adequacy_ = add_fields(gcdi_KPI_adequacy_, model_type = sol['model_type'], solution_id = s)

    gcd_KPI_adequacy.append(gcd_KPI_adequacy_)
    gcdi_KPI_adequacy.append(gcdi_KPI_adequacy_)

# s_uc = combine_solutions(s_uc)
# s_ed = combine_solutions(s_ed)
gcd_KPI_adequacy = pd.concat(gcd_KPI_adequacy)
gcdi_KPI_adequacy = pd.concat(gcdi_KPI_adequacy)

if 'µ' in gcdi_KPI_adequacy.columns: 
#         # out['non-conservative'] = out[['model_type', 'µ']].apply(lambda x: (x[0] !='envelope') + (x[0] =='envelope')*(x[1]<1), axis = 1)
    gcdi_KPI_adequacy['model_type'] = gcdi_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)
    gcd_KPI_adequacy['model_type'] = gcd_KPI_adequacy.apply(lambda x: 'conservative' if (x['model_type'] == 'envelope') & (x['µ'] == 1.0) else x['model_type'], axis=1)

../output/RTS-GMLC_envelope_benchmark_s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_benchmark_s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.8s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.9s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.9s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.10s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.10s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.22s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.22s/all_gcdi_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.24s/all_gcd_KPI_adequacy.parquet
../output/RTS-GMLC_envelope_compare_v1.24s/all_gcdi_KPI_adequacy.parquet

In [3]:
gcd_KPI_adequacy

,model_type,solution_id,configuration,day,OV_uc,E_fixed_cost,E_storage_discharge_MWh,reserve_cost_uc,E_storage_charge_MWh,SOE_0_MWh,...,input_load_uc_MWh,CURE,ELGEN,EOPEX,slack_reserve_up_cost_uc,EENS,reserve_down_uc_MWh,E_input_load_MWh,OPEX_uc,µ
0,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,42411.584442,0.0,2.658124e-10,577492.018767,2.174425e-08,1.289566e-12,14812.458252,42409.966712,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11707.961617,0.029785,3226.496681,12683.7,...,42411.584442,0.0,3.640086e-10,473139.446044,6.366712e-09,1.122578e-12,14812.251179,42409.966712,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11477.471162,0.042446,5849.950564,12683.7,...,37815.376455,0.3,3.872743e-10,512433.607113,2.483200e-09,1.508531e-12,15960.658975,42025.234230,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13906.874641,0.042446,5221.718834,12683.7,...,37815.376455,0.3,1.163587e-09,458327.169219,8.559819e-09,3.550568e-12,15960.649370,42025.234230,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,42411.584442,0.0,0.000000e+00,577492.018767,2.174425e-08,0.000000e+00,14812.458252,42409.966712,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11707.995165,0.029785,3226.530229,12683.7,...,42411.584442,0.0,0.000000e+00,473139.446044,6.366712e-09,0.000000e+00,14812.251179,42409.966712,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11489.262384,0.042446,5861.741786,12683.7,...,37815.376455,0.3,0.000000e+00,512433.607115,2.483200e-09,0.000000e+00,15960.658975,42025.234230,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.8s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13951.640898,0.042446,5266.485090,12683.7,...,37815.376455,0.3,0.000000e+00,458327.169230,8.559819e-09,0.000000e+00,15960.649370,42025.234230,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7022.074357,0.029785,3262.727898,12683.7,...,42411.584442,0.0,4.528816e-12,577492.018767,2.174425e-08,4.529422e-12,14812.458252,42409.966712,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11708.104658,0.029785,3226.639721,12683.7,...,42411.584442,0.0,2.169762e-12,473139.446044,6.366712e-09,2.169525e-12,14812.251179,42409.966712,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,11488.206962,0.042446,5860.686364,12683.7,...,37815.376455,0.3,4.570339e-12,512433.607115,2.483200e-09,4.673548e-12,15960.658975,42025.234230,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.9s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,13941.336786,0.042446,5256.180978,12683.7,...,37815.376455,0.3,1.134167e-11,458327.169227,8.559819e-09,1.133726e-11,15960.649370,42025.234230,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,42411.584442,0.0,1.295853e-15,571018.873984,2.174425e-08,1.296158e-15,14812.458252,42126.249053,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,42411.584442,0.0,1.376248e-12,463176.687400,6.366712e-09,1.376248e-12,14812.251179,42126.249053,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,37815.376456,0.0,4.803482e-16,530619.858898,2.483200e-09,4.803482e-16,15960.658975,43563.011255,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103865,0.042446,3624.646298,12683.7,...,37815.376456,0.0,5.937521e-16,436283.778893,8.559819e-09,5.937515e-16,15960.649370,43563.011255,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.22s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,42411.584442,0.0,8.148829e-14,571018.873984,2.174425e-08,2.855663e-16,14812.458252,42126.249053,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.22s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,42411.584442,0.0,1.955295e-11,463176.687400,6.366712e-09,9.844056e-14,14812.251179,42126.249053,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.22s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,37815.376456,0.0,1.622119e-12,530619.858898,2.483200e-09,8.366604e-15,15960.658975,43563.011255,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.22s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103865,0.042446,3624.646298,12683.7,...,37815.376456,0.0,2.102521e-12,436283.778893,8.559819e-09,1.054581e-14,15960.649370,43563.011255,580563.518382,1.0
0,envelope,RTS-GMLC_envelope_compare_v1.24s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,673344.851286,0.0,7100.401091,0.029785,3349.291564,12683.7,...,42411.584442,0.0,5.872450e-11,571018.873984,2.174425e-08,1.266937e-13,14812.458252,42126.249053,673344.821501,0.5
1,conservative,RTS-GMLC_envelope_compare_v1.24s,base_ramp_storage_envelopes_up_1_dn_1,2,673344.851285,0.0,11978.695841,0.029785,3349.291564,12683.7,...,42411.584442,0.0,1.276611e-12,463176.687400,6.366712e-09,6.427789e-15,14812.251179,42126.249053,673344.821500,1.0
2,envelope,RTS-GMLC_envelope_compare_v1.24s,base_ramp_storage_envelopes_up_0_5_dn_0_5,3,570290.621895,0.0,10150.266454,0.042446,3894.646298,12683.7,...,37815.376456,0.0,4.174584e-13,530619.858898,2.483200e-09,1.360493e-15,15960.658975,43563.011255,570290.579449,0.5
3,conservative,RTS-GMLC_envelope_compare_v1.24s,base_ramp_storage_envelopes_up_1_dn_1,3,580563.560828,0.0,14828.103865,0.042446,3624.646298,12683.7,...,37815.376456,0.0,6.487585e-13,434921.521438,8.559819e-09,3.254016e-15,15960.649370,43563.011255,580563.518382,1.0

In [4]:
values_ = ['reserve_cost_uc','slack_reserve_up_cost_uc','slack_reserve_down_cost_uc','energy_reserve_cost_uc','slack_energy_reserve_up_cost_uc','slack_energy_reserve_down_cost_uc']
values_ += [
    'reserve_up_uc_MWh', 'reserve_down_uc_MWh', 'slack_reserve_up_uc_MWh', 'slack_reserve_down_uc_MWh',
    'required_reserve_up_uc_MWh', 'required_reserve_down_uc_MWh',
    'energy_reserve_up_uc_MWh', 'energy_reserve_down_uc_MWh', 'slack_energy_reserve_up_uc_MWh', 'slack_energy_reserve_down_uc_MWh',
    'required_energy_reserve_up_uc_MWh', 'required_energy_reserve_down_uc_MWh'
]
values_ += ['EOV',]
values_ = [v for v in values_ if v in gcd_KPI_adequacy.columns]
pivot = pd.pivot_table(
    gcd_KPI_adequacy,
    index=['day', 'solution_id'],
    columns='model_type',
    values=values_
)
print(pivot)    
# pivot

                                                EOV                 \
model_type                             conservative       envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s     473139.475829  577492.048552
    RTS-GMLC_envelope_compare_v1.10s  463176.717185  571018.903769
    RTS-GMLC_envelope_compare_v1.22s  463176.717185  571018.903769
    RTS-GMLC_envelope_compare_v1.24s  463176.687400  571018.873984
    RTS-GMLC_envelope_compare_v1.8s   473139.475829  577492.048552
    RTS-GMLC_envelope_compare_v1.9s   473139.475829  577492.048552
3   RTS-GMLC_envelope_benchmark_s     458327.211666  512433.649559
    RTS-GMLC_envelope_compare_v1.10s  436283.821339  530619.901345
    RTS-GMLC_envelope_compare_v1.22s  436283.821339  530619.901345
    RTS-GMLC_envelope_compare_v1.24s  434921.521438  530619.858898
    RTS-GMLC_envelope_compare_v1.8s   458327.211676  512433.649561
    RTS-GMLC_envelope_compare_v1.9s   458327.211673  512433.649561

                                     required_reserve_down_uc_MWh  \
model_type                                           conservative
day solution_id
2   RTS-GMLC_envelope_benchmark_s                    14812.233953
    RTS-GMLC_envelope_compare_v1.10s                 14812.233953
    RTS-GMLC_envelope_compare_v1.22s                 14812.233953
    RTS-GMLC_envelope_compare_v1.24s                 14812.233953
    RTS-GMLC_envelope_compare_v1.8s                  14812.233953
    RTS-GMLC_envelope_compare_v1.9s                  14812.233953
3   RTS-GMLC_envelope_benchmark_s                    15960.645167
    RTS-GMLC_envelope_compare_v1.10s                 15960.645167
    RTS-GMLC_envelope_compare_v1.22s                 15960.645167
    RTS-GMLC_envelope_compare_v1.24s                 15960.645167
    RTS-GMLC_envelope_compare_v1.8s                  15960.645167
    RTS-GMLC_envelope_compare_v1.9s                  15960.645167

                                                   required_reserve_up_uc_MWh  \
model_type                                envelope               conservative
day solution_id
2   RTS-GMLC_envelope_benchmark_s     14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.10s  14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.22s  14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.24s  14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.8s   14812.233953               14972.695060
    RTS-GMLC_envelope_compare_v1.9s   14812.233953               14972.695060
3   RTS-GMLC_envelope_benchmark_s     15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.10s  15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.22s  15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.24s  15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.8s   15960.645167               26485.519376
    RTS-GMLC_envelope_compare_v1.9s   15960.645167               26485.519376

                                                   reserve_cost_uc            \
model_type                                envelope    conservative  envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s     14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.10s  14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.22s  14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.24s  14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.8s   14972.695060        0.029785  0.029785
    RTS-GMLC_envelope_compare_v1.9s   14972.695060        0.029785  0.029785
3   RTS-GMLC_envelope_benchmark_s     26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.10s  26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.22s  26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.24s  26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.8s   26485.519376        0.042446  0.042446
    RTS-GMLC_envelope_compare_v1.9s   26485.519376        0.042446  0.042446

                                     reserve_down_uc_MWh                \
model_type                                  conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s           14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.10s        14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.22s        14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.24s        14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.8s         14812.251179  14812.458252
    RTS-GMLC_envelope_compare_v1.9s         14812.251179  14812.458252
3   RTS-GMLC_envelope_benchmark_s           15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.10s        15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.22s        15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.24s        15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.8s         15960.649370  15960.658975
    RTS-GMLC_envelope_compare_v1.9s         15960.649370  15960.658975

                                     reserve_up_uc_MWh                \
model_type                                conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s         14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.10s      14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.22s      14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.24s      14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.8s       14972.709270  14972.719902
    RTS-GMLC_envelope_compare_v1.9s       14972.709270  14972.719902
3   RTS-GMLC_envelope_benchmark_s         26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.10s      26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.22s      26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.24s      26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.8s       26485.578429  26485.538745
    RTS-GMLC_envelope_compare_v1.9s       26485.578429  26485.538745

                                     slack_reserve_down_cost_uc                \
model_type                                         conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s                  6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.10s               6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.22s               6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.24s               6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.8s                6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.9s                6.366712e-09  2.174425e-08
3   RTS-GMLC_envelope_benchmark_s                  9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.10s               9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.22s               9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.24s               9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.8s                9.083310e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.9s                9.083310e-09  2.483200e-09

                                     slack_reserve_down_uc_MWh                \
model_type                                        conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s                 2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.10s              2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.22s              2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.24s              2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s               2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.9s               2.546685e-11  8.697700e-11
3   RTS-GMLC_envelope_benchmark_s                 3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.10s              3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.22s              3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.24s              3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s               3.633324e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.9s               3.633324e-11  9.932801e-12

                                     slack_reserve_up_cost_uc                \
model_type                                       conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s                6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.10s             6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.22s             6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.24s             6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.8s              6.366712e-09  2.174425e-08
    RTS-GMLC_envelope_compare_v1.9s              6.366712e-09  2.174425e-08
3   RTS-GMLC_envelope_benchmark_s                8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.10s             8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.22s             8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.24s             8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.8s              8.559819e-09  2.483200e-09
    RTS-GMLC_envelope_compare_v1.9s              8.559819e-09  2.483200e-09

                                     slack_reserve_up_uc_MWh
model_type                                      conservative      envelope
day solution_id
2   RTS-GMLC_envelope_benchmark_s               2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.10s            2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.22s            2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.24s            2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.8s             2.546685e-11  8.697700e-11
    RTS-GMLC_envelope_compare_v1.9s             2.546685e-11  8.697700e-11
3   RTS-GMLC_envelope_benchmark_s               3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.10s            3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.22s            3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.24s            3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.8s             3.423928e-11  9.932801e-12
    RTS-GMLC_envelope_compare_v1.9s             3.423928e-11  9.932801e-12

In [5]:
values_

['reserve_cost_uc',
 'slack_reserve_up_cost_uc',
 'slack_reserve_down_cost_uc',
 'reserve_up_uc_MWh',
 'reserve_down_uc_MWh',
 'slack_reserve_up_uc_MWh',
 'slack_reserve_down_uc_MWh',
 'required_reserve_up_uc_MWh',
 'required_reserve_down_uc_MWh',
 'EOV']

In [6]:
# pivot.to_csv('pivot.csv')
# gcd_KPI_adequacy.to_csv('test.csv')
#

In [7]:
from itertools import product

days = [2]
scalar = []
for sol, day in product(ss, days):
    s = sol['solution_folder']
    scalar_ = pd.read_parquet(os.path.join("..", "output", s, f'n_{day}','s_ed_scalar.parquet'))
    scalar_['day'] = day
    scalar_['solution_id'] = sol['solution_folder']
    # scalar_.model_type = sol['model_type']
    scalar.append(scalar_)        

scalar = pd.concat(scalar)

In [8]:
scalar

,objective_value,termination_status,OPEX,iteration,day,configuration,solution_id
0,450946.521613,OPTIMAL,450946.491828,demand_86,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
1,390804.266707,OPTIMAL,390804.236922,demand_91,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
2,478871.229947,OPTIMAL,478871.200162,demand_48,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
3,549114.153620,OPTIMAL,549114.123835,demand_21,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
4,393903.636144,OPTIMAL,393903.606359,demand_16,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_benchmark_s
...,...,...,...,...,...,...,...
1,571018.903769,OPTIMAL,571018.873984,demand_1,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.10s
0,463176.717185,OPTIMAL,463176.687400,demand_1,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.22s
1,571018.903769,OPTIMAL,571018.873984,demand_1,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.22s
0,463176.717185,OPTIMAL,463176.687400,demand_1,2,base_ramp_storage_envelopes_up_1_dn_1,RTS-GMLC_envelope_compare_v1.24s
1,571018.903769,OPTIMAL,571018.873984,demand_1,2,base_ramp_storage_envelopes_up_0_5_dn_0_5,RTS-GMLC_envelope_compare_v1.24s

In [9]:
gcdi_KPI_adequacy = gcdi_KPI_adequacy.merge(
    scalar[['solution_id', 'configuration', 'day', 'objective_value', 'iteration']],
    on=['solution_id', 'configuration', 'day','iteration'],
    suffixes=('', '_s')
)

In [10]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') #&  (gcdi_KPI_adequacy.day == 3)
for k,v in gcdi_KPI_adequacy.loc[filter_,:].groupby(['day', 'µ', 'model_type']):
    print(v[['objective_value', 'objective_value_s', 'day', 'µ', 'model_type']])

     objective_value  objective_value_s  day    µ model_type
165    571018.903769      571018.903769    2  0.5   envelope
365    571018.903769      571018.903769    2  0.5   envelope
565    571018.903769      571018.903769    2  0.5   envelope
601    571018.903769      571018.903769    2  0.5   envelope
603    571018.903769      571018.903769    2  0.5   envelope
605    571018.873984      571018.903769    2  0.5   envelope
     objective_value  objective_value_s  day    µ    model_type
65     463176.717185      463176.717185    2  1.0  conservative
265    463176.717185      463176.717185    2  1.0  conservative
465    463176.717185      463176.717185    2  1.0  conservative
600    463176.717185      463176.717185    2  1.0  conservative
602    463176.717185      463176.717185    2  1.0  conservative
604    463176.687400      463176.717185    2  1.0  conservative

In [11]:
gcdi_KPI_adequacy['OV_reserve'] = gcdi_KPI_adequacy.objective_value - gcdi_KPI_adequacy.reserve_cost

In [12]:
filter_ = (gcdi_KPI_adequacy.iteration == 'demand_1') #&  (gcdi_KPI_adequacy.day == 3)
for k,v in gcdi_KPI_adequacy.loc[filter_,:].groupby(['day', 'µ', 'model_type']):
    print(v[['objective_value_uc','objective_value', 'objective_value_s', 'OV_reserve', 'day', 'µ']])

     objective_value_uc  objective_value  objective_value_s     OV_reserve  \
165       673344.851286    571018.903769      571018.903769  571018.873984
365       673344.851286    571018.903769      571018.903769  571018.873984
565       673344.851286    571018.903769      571018.903769  571018.873984
601       673344.851286    571018.903769      571018.903769  571018.873984
603       673344.851286    571018.903769      571018.903769  571018.873984
605       673344.851286    571018.873984      571018.903769            NaN

     day    µ
165    2  0.5
365    2  0.5
565    2  0.5
601    2  0.5
603    2  0.5
605    2  0.5
     objective_value_uc  objective_value  objective_value_s   OV_reserve  day  \
65        673344.851285    463176.717185      463176.717185  463176.6874    2
265       673344.851285    463176.717185      463176.717185  463176.6874    2
465       673344.851285    463176.717185      463176.717185  463176.6874    2
600       673344.851285    463176.717185      463176.717185  463176.6874    2
602       673344.851285    463176.717185      463176.717185  463176.6874    2
604       673344.851285    463176.687400      463176.717185          NaN    2

       µ
65   1.0
265  1.0
465  1.0
600  1.0
602  1.0
604  1.0

In [13]:
gcdi_KPI_adequacy

,model_type,solution_id,configuration,day,iteration,LLD_h,ENS_MWh,input_load_MWh,CURD_h,CUR_MWh,...,avg_marginal_reserve_down_price_uc_MU_MWh,input_load_uc_MWh,reserve_up_uc_MWh,slack_reserve_up_uc_MWh,reserve_down_uc_MWh,required_reserve_up_uc_MWh,required_reserve_down_uc_MWh,slack_reserve_down_uc_MWh,objective_value_s,OV_reserve
0,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_86,0,3.714700e-14,41497.991268,0,0.0,...,None,42411.584442,14972.709270,2.546685e-11,14812.251179,14972.69506,14812.233953,2.546685e-11,450946.521613,450946.491828
1,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_91,0,3.347293e-17,38482.750638,0,0.0,...,None,42411.584442,14972.709270,2.546685e-11,14812.251179,14972.69506,14812.233953,2.546685e-11,390804.266707,390804.236922
2,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_48,0,7.594515e-14,42991.007672,0,0.0,...,None,42411.584442,14972.709270,2.546685e-11,14812.251179,14972.69506,14812.233953,2.546685e-11,478871.229947,478871.200162
3,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_21,0,1.050402e-14,46377.127336,0,0.0,...,None,42411.584442,14972.709270,2.546685e-11,14812.251179,14972.69506,14812.233953,2.546685e-11,549114.153620,549114.123835
4,conservative,RTS-GMLC_envelope_benchmark_s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_16,0,3.143277e-12,38704.887948,0,0.0,...,None,42411.584442,14972.709270,2.546685e-11,14812.251179,14972.69506,14812.233953,2.546685e-11,393903.636144,393903.606359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,envelope,RTS-GMLC_envelope_compare_v1.10s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,1.296158e-15,42126.249053,0,0.0,...,None,42411.584442,14972.719902,8.697700e-11,14812.458252,14972.69506,14812.233953,8.697700e-11,571018.903769,571018.873984
602,conservative,RTS-GMLC_envelope_compare_v1.22s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,9.844056e-14,42126.249053,0,0.0,...,None,42411.584442,14972.709270,2.546685e-11,14812.251179,14972.69506,14812.233953,2.546685e-11,463176.717185,463176.687400
603,envelope,RTS-GMLC_envelope_compare_v1.22s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,2.855663e-16,42126.249053,0,0.0,...,None,42411.584442,14972.719902,8.697700e-11,14812.458252,14972.69506,14812.233953,8.697700e-11,571018.903769,571018.873984
604,conservative,RTS-GMLC_envelope_compare_v1.24s,base_ramp_storage_envelopes_up_1_dn_1,2,demand_1,0,6.427789e-15,42126.249053,0,0.0,...,None,42411.584442,14972.709270,2.546685e-11,14812.251179,14972.69506,14812.233953,2.546685e-11,463176.717185,NaN
605,envelope,RTS-GMLC_envelope_compare_v1.24s,base_ramp_storage_envelopes_up_0_5_dn_0_5,2,demand_1,0,1.266937e-13,42126.249053,0,0.0,...,None,42411.584442,14972.719902,8.697700e-11,14812.458252,14972.69506,14812.233953,8.697700e-11,571018.903769,NaN

In [14]:
x = 436283.821342
y = 436283.821339
print( (x-y)/y)

6.876176674651827e-12